"""Tab completion support for memory_tool commands.

Generates shell completion scripts for bash, zsh, and PowerShell.
"""

import sys
from pathlib import Path
from typing import Optional, List


class CompletionError(Exception):
    """Base exception for completion operations."""
    pass


class CompletionManager:
    """Manage shell completion scripts."""

    def __init__(self):
        """Initialize completion manager."""
        pass

    def generate_completion(self, shell: str) -> str:
        """Generate completion script for specified shell.

        Args:
            shell: Shell type ("bash", "zsh", "powershell")

        Returns:
            Completion script content

        Raises:
            CompletionError: If shell type is unsupported
        """
        if shell not in ["bash", "zsh", "powershell"]:
            raise CompletionError(f"Unsupported shell: {shell}")

        # Define commands and their options
        commands = {
            "record": ["--date", "--time"],
            "init": [],
            "search": ["--all", "--with-kb", "--no-kb", "--case-sensitive", "--context", "--limit",
                      "--from-date", "--to-date", "--no-index", "--semantic", "--hybrid",
                      "--text-weight", "--semantic-weight", "--no-cache", "--cache-ttl"],
            "context": ["--output"],
            "today": [],
            "week": [],
            "status": [],
            "alias": ["--powershell"],
            "summary": ["--period", "--date", "--from-date", "--to-date", "--module", "--output"],
            "browse": [],
            "completion": ["--output", "--profile"],
            "index": ["--check", "--stats", "--force", "--optimize", "--vacuum"],
            "archive": ["--phase", "--up-to", "--keep-recent", "--dry-run"],
        }

        # Subcommands for specific commands
        subcommands = {
            "alias": ["install", "uninstall", "list"],
            "completion": ["generate", "install", "uninstall", "status"],
            "archive": ["decisions", "current", "plans"],
        }

        if shell == "bash":
            return self._generate_bash_completion(commands, subcommands)
        elif shell == "zsh":
            return self._generate_zsh_completion(commands, subcommands)
        elif shell == "powershell":
            return self._generate_powershell_completion(commands, subcommands)

    def _generate_bash_completion(self, commands: dict, subcommands: dict) -> str:
        """Generate bash completion script."""
        cmd_list = " ".join(commands.keys())

        script = f"""# bash completion for memory-tool
# Generated by memory-tool completion system

_memory_tool_completion() {{
    local cur prev opts
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"

    # Main commands
    local commands="{cmd_list}"

    # If we're completing the first argument (command)
    if [ $COMP_CWORD -eq 1 ]; then
        COMPREPLY=( $(compgen -W "$commands" -- $cur) )
        return 0
    fi

    # Get the command being completed
    local cmd="${{COMP_WORDS[1]}}"

    # Command-specific completions
    case "$cmd" in
"""

        for cmd, opts in commands.items():
            if opts or cmd in subcommands:
                script += f"        {cmd})\n"
                if cmd in subcommands:
                    script += f"            local subcmds=\"{' '.join(subcommands[cmd])}\"\n"
                    script += f"            if [ $COMP_CWORD -eq 2 ]; then\n"
                    script += f"                COMPREPLY=( $(compgen -W \"$subcmds\" -- $cur) )\n"
                    script += f"            else\n"
                if opts:
                    script += f"                local opts=\"{' '.join(opts)}\"\n"
                    script += f"                COMPREPLY=( $(compgen -W \"$opts\" -- $cur) )\n"
                if cmd in subcommands and opts:
                    script += f"            fi\n"
                script += f"            ;;\n"

        script += """        *)
            ;;
    esac
}

# Register completion
complete -F _memory_tool_completion m
complete -F _memory_tool_completion minit
complete -F _memory_tool_completion ms
complete -F _memory_tool_completion mcontext
complete -F _memory_tool_completion mtoday
complete -F _memory_tool_completion mweek
complete -F _memory_tool_completion mstatus
complete -F _memory_tool_completion malias
complete -F _memory_tool_completion msummary
complete -F _memory_tool_completion mbrowse
complete -F _memory_tool_completion mcompletion
complete -F _memory_tool_completion mindex
complete -F _memory_tool_completion marchive
"""
        return script

    def _generate_zsh_completion(self, commands: dict, subcommands: dict) -> str:
        """Generate zsh completion script."""
        script = """#compdef m minit ms mcontext mtoday mweek mstatus malias msummary mbrowse mcompletion mindex marchive

# zsh completion for memory-tool
# Generated by memory-tool completion system

_memory_tool() {
    local -a commands
    commands=(
"""
        for cmd in commands.keys():
            script += f"        '{cmd}:Memory tool command'\n"

        script += """    )

    _arguments -C \\
        '1: :->command' \\
        '*:: :->args'

    case $state in
        command)
            _describe 'command' commands
            ;;
        args)
            case $words[1] in
"""

        for cmd, opts in commands.items():
            if opts or cmd in subcommands:
                script += f"                {cmd})\n"
                if cmd in subcommands:
                    script += f"                    local -a subcmds\n"
                    script += f"                    subcmds=(\n"
                    for sub in subcommands[cmd]:
                        script += f"                        '{sub}'\n"
                    script += f"                    )\n"
                    script += f"                    _describe 'subcommand' subcmds\n"
                if opts:
                    script += f"                    _arguments \\\n"
                    for opt in opts:
                        script += f"                        '{opt}[Option]' \\\n"
                    script = script.rstrip(" \\\n") + "\n"
                script += f"                    ;;\n"

        script += """            esac
            ;;
    esac
}

_memory_tool "$@"
"""
        return script

    def _generate_powershell_completion(self, commands: dict, subcommands: dict) -> str:
        """Generate PowerShell completion script."""
        cmd_list = ", ".join(f"'{cmd}'" for cmd in commands.keys())

        script = f"""# PowerShell completion for memory-tool
# Generated by memory-tool completion system

$commands = @({cmd_list})

Register-ArgumentCompleter -Native -CommandName m,minit,ms,mcontext,mtoday,mweek,mstatus,malias,msummary,mbrowse,mcompletion,mindex,marchive -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)

    $tokens = $commandAst.ToString().Split(' ')

    # Complete main command
    if ($tokens.Count -le 1 -or ($tokens.Count -eq 2 -and $wordToComplete)) {{
        $commands | Where-Object {{ $_ -like "$wordToComplete*" }} | ForEach-Object {{
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }}
        return
    }}

    # Get the main command
    $mainCmd = $tokens[1]

    # Command-specific completions
    switch ($mainCmd) {{
"""

        for cmd, opts in commands.items():
            if opts or cmd in subcommands:
                script += f"        '{cmd}' {{\n"
                if cmd in subcommands:
                    subcmd_list = ", ".join(f"'{sub}'" for sub in subcommands[cmd])
                    script += f"            $subcommands = @({subcmd_list})\n"
                    script += f"            if ($tokens.Count -le 2) {{\n"
                    script += f"                $subcommands | Where-Object {{ $_ -like \"$wordToComplete*\" }} | ForEach-Object {{\n"
                    script += f"                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)\n"
                    script += f"                }}\n"
                    script += f"            }}\n"
                if opts:
                    opts_list = ", ".join(f"'{opt}'" for opt in opts)
                    script += f"            $options = @({opts_list})\n"
                    script += f"            $options | Where-Object {{ $_ -like \"$wordToComplete*\" }} | ForEach-Object {{\n"
                    script += f"                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)\n"
                    script += f"            }}\n"
                script += f"        }}\n"

        script += """    }
}}
"""
        return script

    def get_install_instructions(self, shell: str) -> List[str]:
        """Get installation instructions for completion script.

        Args:
            shell: Shell type

        Returns:
            List of instruction strings
        """
        if shell == "bash":
            return [
                "# Add to ~/.bashrc or ~/.bash_profile:",
                "eval \"$(python -m memory_tool completion generate bash)\"",
                "",
                "# Or save to completion directory:",
                "python -m memory_tool completion generate bash > ~/.local/share/bash-completion/completions/memory-tool",
            ]
        elif shell == "zsh":
            return [
                "# Add to ~/.zshrc:",
                "eval \"$(python -m memory_tool completion generate zsh)\"",
                "",
                "# Or save to completion directory:",
                "python -m memory_tool completion generate zsh > ~/.zsh/completion/_memory-tool",
                "# Make sure fpath includes ~/.zsh/completion",
            ]
        elif shell == "powershell":
            return [
                "# Add to PowerShell profile:",
                "python -m memory_tool completion generate powershell | Out-String | Invoke-Expression",
                "",
                "# Or save to profile:",
                "python -m memory_tool completion generate powershell >> $PROFILE",
            ]
        else:
            return ["Unsupported shell type"]

    def install_completion(
        self,
        shell: str,
        output_file: Optional[Path] = None,
        append_to_profile: bool = False
    ) -> Path:
        """Install completion script.

        Args:
            shell: Shell type
            output_file: Output file path (auto-detected if None)
            append_to_profile: Append to shell profile instead of separate file

        Returns:
            Path where completion was installed

        Raises:
            CompletionError: If installation fails
        """
        # Generate completion script
        script = self.generate_completion(shell)

        # Determine output path
        if output_file is None:
            output_file = self._get_default_completion_path(shell, append_to_profile)

        # Ensure parent directory exists
        output_file.parent.mkdir(parents=True, exist_ok=True)

        # Write or append script
        try:
            if append_to_profile:
                # Append to existing profile
                with open(output_file, 'a', encoding='utf-8') as f:
                    f.write("\n# Memory Tool completion\n")
                    f.write(script)
                    f.write("\n")
            else:
                # Write to separate file
                with open(output_file, 'w', encoding='utf-8') as f:
                    f.write(script)

            return output_file

        except Exception as e:
            raise CompletionError(f"Failed to install completion: {e}")

    def _get_default_completion_path(
        self,
        shell: str,
        append_to_profile: bool
    ) -> Path:
        """Get default completion installation path.

        Args:
            shell: Shell type
            append_to_profile: Whether appending to profile

        Returns:
            Default path for completion script
        """
        home = Path.home()

        if append_to_profile:
            # Return profile path
            if shell == "bash":
                # Try .bashrc first, fall back to .bash_profile
                bashrc = home / ".bashrc"
                bash_profile = home / ".bash_profile"
                return bashrc if bashrc.exists() else bash_profile
            elif shell == "zsh":
                return home / ".zshrc"
            elif shell == "powershell":
                # Use PROFILE environment variable if available
                if sys.platform == "win32":
                    # Windows PowerShell profile
                    docs = Path.home() / "Documents"
                    ps_dir = docs / "WindowsPowerShell"
                    ps_dir.mkdir(parents=True, exist_ok=True)
                    return ps_dir / "Microsoft.PowerShell_profile.ps1"
                else:
                    # Unix PowerShell profile
                    return home / ".config" / "powershell" / "profile.ps1"
        else:
            # Return separate completion file path
            if shell == "bash":
                comp_dir = home / ".local" / "share" / "bash-completion" / "completions"
                comp_dir.mkdir(parents=True, exist_ok=True)
                return comp_dir / "memory-tool"
            elif shell == "zsh":
                comp_dir = home / ".zsh" / "completion"
                comp_dir.mkdir(parents=True, exist_ok=True)
                return comp_dir / "_memory-tool"
            elif shell == "powershell":
                # PowerShell doesn't have a standard completion directory
                # Use profile directory
                if sys.platform == "win32":
                    docs = Path.home() / "Documents"
                    ps_dir = docs / "WindowsPowerShell"
                    ps_dir.mkdir(parents=True, exist_ok=True)
                    return ps_dir / "memory-tool-completion.ps1"
                else:
                    config_dir = home / ".config" / "powershell"
                    config_dir.mkdir(parents=True, exist_ok=True)
                    return config_dir / "memory-tool-completion.ps1"

        raise CompletionError(f"Unsupported shell: {shell}")

    def uninstall_completion(self, shell: str) -> bool:
        """Uninstall completion script.

        Args:
            shell: Shell type

        Returns:
            True if completion was uninstalled, False if not found
        """
        # Get default paths
        paths_to_check = [
            self._get_default_completion_path(shell, append_to_profile=False),
            self._get_default_completion_path(shell, append_to_profile=True),
        ]

        removed = False
        for path in paths_to_check:
            if path.exists():
                try:
                    # If it's a profile file, we can't just delete it
                    # User needs to manually remove the completion section
                    if path.name in [".bashrc", ".bash_profile", ".zshrc", "profile.ps1"]:
                        # Don't delete profile, just inform user
                        continue
                    else:
                        # Delete completion file
                        path.unlink()
                        removed = True
                except Exception:
                    pass

        return removed

    def check_installation(self, shell: str) -> bool:
        """Check if completion is installed for shell.

        Args:
            shell: Shell type

        Returns:
            True if completion is installed
        """
        # Check default paths
        paths_to_check = [
            self._get_default_completion_path(shell, append_to_profile=False),
        ]

        for path in paths_to_check:
            if path.exists():
                return True

        return False
