"""Interactive tutorial system for memory_tool."""

from typing import List, Dict, Optional
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt


class Tutorial:
    """Interactive tutorial for memory_tool commands."""

    def __init__(self, lang: str = "en"):
        """Initialize tutorial.

        Args:
            lang: Language for tutorial content ('en' or 'ko')
        """
        self.console = Console()
        self.lang = lang
        self.lessons = self._get_lessons()

    def _get_lessons(self) -> List[Dict]:
        """Get tutorial lessons based on language.

        Returns:
            List of lesson dictionaries
        """
        if self.lang == "ko":
            return self._get_korean_lessons()
        return self._get_english_lessons()

    def _get_english_lessons(self) -> List[Dict]:
        """Get English tutorial lessons."""
        return [
            # ============================================================
            # LESSON 1: Installation
            # ============================================================
            {
                "id": "installation",
                "title": "Installation & Setup",
                "description": "Install memory_tool and set up your first project",
                "content": [
                    "[bold cyan]STEP 1: Install memory_tool[/bold cyan]",
                    "",
                    "  Option A - From PyPI (recommended):",
                    "    pip install memory-tool",
                    "",
                    "  Option B - From source:",
                    "    git clone https://github.com/your-repo/memory_tool.git",
                    "    cd memory_tool",
                    "    pip install -e .",
                    "",
                    "  Optional features:",
                    "    pip install memory-tool[llm]     # LLM integration (mask, msummary)",
                    "    pip install memory-tool[vector]  # Semantic search",
                    "    pip install memory-tool[tui]     # Interactive browser (mbrowse)",
                    "",
                    "[bold cyan]STEP 2: Verify Installation[/bold cyan]",
                    "",
                    "  Run these commands to verify:",
                    "    python -m memory_tool --help     # Should show help",
                    "    mhelp                            # Quick help reference",
                    "",
                    "[bold cyan]STEP 3: Initialize Your Project[/bold cyan]",
                    "",
                    "  Navigate to your project directory and run:",
                    "    cd /path/to/your/project",
                    "    minit",
                    "",
                    "  This creates:",
                    "    .memory/           # Memory storage directory",
                    "    ├── timeline/      # Time-based records",
                    "    ├── modules/       # Module-based organization",
                    "    ├── config.yaml    # Configuration file",
                    "    └── docs/          # Documentation templates",
                    "",
                    "    .claude/           # Claude Code integration",
                    "    ├── skills/        # Memory tool skills",
                    "    └── guidelines.md  # Usage guidelines",
                    "",
                    "[bold cyan]STEP 4: Install Command Aliases[/bold cyan]",
                    "",
                    "  For convenient short commands (m, ms, mtoday, etc.):",
                    "",
                    "  Windows PowerShell:",
                    "    malias install --powershell",
                    "    . $PROFILE                       # Reload profile",
                    "",
                    "  Linux/macOS Bash:",
                    "    malias install --bash",
                    "    source ~/.bashrc                 # Reload profile",
                    "",
                    "  Linux/macOS Zsh:",
                    "    malias install --zsh",
                    "    source ~/.zshrc                  # Reload profile",
                    "",
                    "[bold yellow]Next:[/bold yellow] Run [bold]mtutorial setup[/bold] to configure CLAUDE.md",
                ],
            },
            # ============================================================
            # LESSON 2: Setup (CLAUDE.md Configuration)
            # ============================================================
            {
                "id": "setup",
                "title": "CLAUDE.md Setup for AI Integration",
                "description": "Configure your project for Claude Code and other AI tools",
                "content": [
                    "[bold cyan]WHY CLAUDE.md?[/bold cyan]",
                    "",
                    "  CLAUDE.md is the entry point for AI coding assistants.",
                    "  Claude Code reads this file automatically at session start.",
                    "  Other AI tools (Gemini CLI, ChatGPT) can use it as context.",
                    "",
                    "[bold cyan]STEP 1: Create CLAUDE.md[/bold cyan]",
                    "",
                    "  Copy the template to your project root:",
                    "",
                    "    # The template is at:",
                    "    .memory/templates/CLAUDE.md.template",
                    "",
                    "    # Copy it to project root:",
                    "    cp .memory/templates/CLAUDE.md.template CLAUDE.md",
                    "",
                    "[bold cyan]STEP 2: Edit CLAUDE.md[/bold cyan]",
                    "",
                    "  Minimum required content:",
                    "",
                    "    ┌─────────────────────────────────────────────────────────┐",
                    "    │ # For Claude Code                                       │",
                    "    │                                                         │",
                    "    │ ## Context Files                                        │",
                    "    │                                                         │",
                    "    │ **Always read these files first:**                      │",
                    "    │ - `.claude/memory-context.md` - Current project state   │",
                    "    │ - `.claude/guidelines.md` - Memory tool usage guide     │",
                    "    │                                                         │",
                    "    │ ## Quick Commands                                       │",
                    "    │                                                         │",
                    "    │ ```bash                                                 │",
                    "    │ m \"message\"    # Record to timeline                    │",
                    "    │ mcontext       # Build context for AI                   │",
                    "    │ ms \"query\"     # Search                                │",
                    "    │ ```                                                     │",
                    "    │                                                         │",
                    "    │ **Run `mcontext` before AI sessions.**                  │",
                    "    └─────────────────────────────────────────────────────────┘",
                    "",
                    "[bold cyan]STEP 3: Add Project-Specific Content[/bold cyan]",
                    "",
                    "  Customize CLAUDE.md with your project information:",
                    "",
                    "    ## Project Overview",
                    "    [Describe your project purpose]",
                    "",
                    "    ## Technical Stack",
                    "    [List technologies: Python 3.12, FastAPI, PostgreSQL, etc.]",
                    "",
                    "    ## Development Workflow",
                    "    [Your branching strategy, PR process, etc.]",
                    "",
                    "    ## Code Conventions",
                    "    [Naming conventions, patterns to follow]",
                    "",
                    "[bold cyan]STEP 4: Generate Context[/bold cyan]",
                    "",
                    "  Run mcontext to create the context file:",
                    "    mcontext",
                    "",
                    "  This creates: .claude/memory-context.md",
                    "  (Auto-generated, don't edit manually)",
                    "",
                    "[bold cyan]STEP 5: Verify Setup[/bold cyan]",
                    "",
                    "  Check that these files exist:",
                    "    CLAUDE.md                    # Your project instructions",
                    "    .claude/guidelines.md       # Memory tool guide",
                    "    .claude/memory-context.md   # Generated context",
                    "",
                    "[bold yellow]Important:[/bold yellow]",
                    "  - Run [bold]mcontext[/bold] before every AI session",
                    "  - CLAUDE.md is read-only for AI (it follows your instructions)",
                    "  - memory-context.md is generated (shows current state)",
                ],
            },
            # ============================================================
            # LESSON 3: Daily Workflow
            # ============================================================
            {
                "id": "daily",
                "title": "Daily Workflow",
                "description": "How to use memory_tool in your daily work",
                "content": [
                    "[bold cyan]MORNING ROUTINE[/bold cyan]",
                    "",
                    "  1. Update context before starting AI session:",
                    "     mcontext",
                    "",
                    "  2. Check yesterday's work:",
                    "     mtoday                # Today's timeline",
                    "     mdays 2               # Last 2 days",
                    "",
                    "  3. Start your AI assistant:",
                    "     claude                # Claude Code",
                    "     gemini                # Gemini CLI",
                    "",
                    "[bold cyan]DURING WORK[/bold cyan]",
                    "",
                    "  Record at [bold]natural breakpoints[/bold] - NOT during deep work!",
                    "",
                    "  [bold green]Good times to record:[/bold green]",
                    "    ✓ After completing a feature",
                    "    ✓ After making a decision",
                    "    ✓ After fixing a bug",
                    "    ✓ Before taking a break",
                    "",
                    "  [bold red]Avoid recording:[/bold red]",
                    "    ✗ During coding flow",
                    "    ✗ Every small change",
                    "    ✗ Trivial questions/answers",
                    "",
                    "  [bold]Recording Examples:[/bold]",
                    "",
                    "    m \"Feature complete: user authentication with JWT\"",
                    "    m \"Decision: Using PostgreSQL for relational data, Redis for cache\"",
                    "    m \"Fixed: memory leak in worker threads by limiting pool size\"",
                    "    m \"Blocker: API rate limit hit, need to implement backoff\"",
                    "",
                    "[bold cyan]SEARCHING[/bold cyan]",
                    "",
                    "  Local search (current project):",
                    "    ms \"authentication\"",
                    "",
                    "  Include knowledge base (all projects):",
                    "    ms \"authentication\" --with-kb",
                    "",
                    "  Semantic search (requires vector extra):",
                    "    ms --semantic \"how to handle auth errors\"",
                    "",
                    "[bold cyan]END OF DAY[/bold cyan]",
                    "",
                    "  Review today's work:",
                    "    mtoday",
                    "",
                    "  Check statistics:",
                    "    mstatus",
                    "",
                    "[bold yellow]Key Principle:[/bold yellow]",
                    "  \"Capture in 0.5 seconds, organize on weekends, use for life.\"",
                    "  Don't overthink - just record the key points!",
                ],
            },
            # ============================================================
            # LESSON 4: AI Integration (Detailed)
            # ============================================================
            {
                "id": "ai-integration",
                "title": "AI Tool Integration (Detailed)",
                "description": "Complete guide for Claude Code, Gemini CLI, and other AI tools",
                "content": [
                    "[bold cyan]OVERVIEW[/bold cyan]",
                    "",
                    "  memory_tool provides context to AI assistants:",
                    "  - Timeline: What you've worked on recently",
                    "  - Modules: How your knowledge is organized",
                    "  - Plans: What you're currently working on",
                    "",
                    "  [bold]Two Usage Modes:[/bold]",
                    "  1. [bold]Interactive Mode[/bold] - Use AI CLI directly (claude, gemini)",
                    "  2. [bold]Headless Mode[/bold] - Use mask command for quick Q&A",
                    "",
                    "-----------------------------------------------------------",
                    "[bold cyan]CLAUDE CODE & GEMINI CLI (Similar Usage)[/bold cyan]",
                    "-----------------------------------------------------------",
                    "",
                    "  Both Claude Code and Gemini CLI work the same way:",
                    "  - Both provide interactive mode",
                    "  - Both support headless mode (for mask command)",
                    "  - Both read context files automatically",
                    "",
                    "  [bold]Installation:[/bold]",
                    "",
                    "    Claude Code:",
                    "      npm install -g @anthropic-ai/claude-code",
                    "",
                    "    Gemini CLI:",
                    "      npm install -g @anthropic-ai/gemini-cli",
                    "      # or: pip install google-genai",
                    "",
                    "-----------------------------------------------------------",
                    "[bold cyan]MODE 1: INTERACTIVE MODE[/bold cyan]",
                    "-----------------------------------------------------------",
                    "",
                    "  [bold]Setup (same for both):[/bold]",
                    "    1. CLAUDE.md in project root (or GEMINI.md)",
                    "    2. .claude/guidelines.md exists",
                    "    3. Run mcontext before starting",
                    "",
                    "  [bold]Workflow:[/bold]",
                    "",
                    "    # 1. Generate fresh context",
                    "    mcontext",
                    "",
                    "    # 2. Start your preferred AI CLI",
                    "    claude                          # Claude Code",
                    "    gemini                          # Gemini CLI",
                    "",
                    "    # 3. AI automatically reads:",
                    "    #    - CLAUDE.md / GEMINI.md (your instructions)",
                    "    #    - .claude/memory-context.md (current state)",
                    "    #    - .claude/guidelines.md (memory tool guide)",
                    "",
                    "    # 4. After completing work, record it",
                    "    m \"Completed: implemented user auth\"",
                    "",
                    "  [bold]Context Options:[/bold]",
                    "",
                    "    mcontext                        # Basic context",
                    "    mcontext --with-map             # Include code structure",
                    "    mcontext --structure            # Include file structure",
                    "",
                    "-----------------------------------------------------------",
                    "[bold cyan]MODE 2: HEADLESS MODE (mask command)[/bold cyan]",
                    "-----------------------------------------------------------",
                    "",
                    "  Use AI for quick Q&A without entering interactive mode.",
                    "  Both Claude CLI and Gemini CLI support headless execution.",
                    "",
                    "  [bold]Step 1: Configure LLM provider in .memory/config.yaml[/bold]",
                    "",
                    "    # For Claude CLI:",
                    "    llm:",
                    "      provider: claude-cli",
                    "      claude_cli:",
                    "        command: claude            # CLI command name",
                    "        model: null                # null = use CLI default",
                    "",
                    "    # For Gemini CLI:",
                    "    llm:",
                    "      provider: gemini-cli",
                    "      gemini_cli:",
                    "        command: gemini            # CLI command name",
                    "        model: null                # null = use CLI default",
                    "",
                    "  [bold]Step 2: Use mask command[/bold]",
                    "",
                    "    # Ask questions about your memory (RAG-powered)",
                    "    mask \"What decisions did I make about authentication?\"",
                    "    mask \"Summarize my work this week\"",
                    "    mask \"What blockers did I encounter?\"",
                    "",
                    "  [bold]How mask works:[/bold]",
                    "    1. Searches your memory for relevant context",
                    "    2. Builds a prompt with the context",
                    "    3. Sends to AI via headless mode",
                    "    4. Returns the answer",
                    "",
                    "-----------------------------------------------------------",
                    "[bold cyan]OTHER AI TOOLS (ChatGPT, API, etc.)[/bold cyan]",
                    "-----------------------------------------------------------",
                    "",
                    "  For AI tools without CLI integration:",
                    "",
                    "    # 1. Generate context",
                    "    mcontext",
                    "",
                    "    # 2. Copy context file content",
                    "    cat .claude/memory-context.md       # Linux/macOS",
                    "    type .claude\\memory-context.md     # Windows",
                    "",
                    "    # 3. Paste into your AI chat as context",
                    "",
                    "  For Anthropic/OpenAI API usage:",
                    "",
                    "    llm:",
                    "      provider: anthropic",
                    "      anthropic:",
                    "        api_key: null              # Or set ANTHROPIC_API_KEY",
                    "        model: claude-3-5-sonnet-20241022",
                    "",
                    "[bold yellow]TIP:[/bold yellow] Search before asking AI:",
                    "    ms \"authentication\" --with-kb",
                    "    # Share relevant results with AI for better answers",
                ],
            },
            # ============================================================
            # LESSON 5: Recording Best Practices
            # ============================================================
            {
                "id": "recording",
                "title": "Recording Best Practices",
                "description": "What, when, and how to record effectively",
                "content": [
                    "[bold cyan]WHAT TO RECORD[/bold cyan]",
                    "",
                    "  [bold green]✓ RECORD these:[/bold green]",
                    "",
                    "    Decisions:",
                    "      m \"Decision: Using TypeScript for type safety\"",
                    "      m \"Decision: PostgreSQL over MongoDB for relational data\"",
                    "",
                    "    Completions:",
                    "      m \"Feature complete: user registration with email verification\"",
                    "      m \"Refactoring complete: extracted auth logic to separate module\"",
                    "",
                    "    Bug fixes:",
                    "      m \"Fixed: race condition in concurrent file uploads\"",
                    "      m \"Fixed: null pointer in user profile loading\"",
                    "",
                    "    Blockers/Issues:",
                    "      m \"Blocker: third-party API down, waiting for fix\"",
                    "      m \"Issue: performance degradation after 1000 users\"",
                    "",
                    "    Insights/Learning:",
                    "      m \"TIL: Redis SCAN is better than KEYS for large datasets\"",
                    "      m \"Insight: batch processing reduces API calls by 80%\"",
                    "",
                    "  [bold red]✗ DON'T RECORD these:[/bold red]",
                    "",
                    "    ✗ Trivial changes: \"Fixed typo\"",
                    "    ✗ Work in progress: \"Working on auth...\"",
                    "    ✗ Obvious things: \"Added import statement\"",
                    "    ✗ Every conversation: \"Asked Claude about X\"",
                    "",
                    "[bold cyan]RECORDING FORMAT[/bold cyan]",
                    "",
                    "  Use prefixes for easy searching:",
                    "",
                    "    Decision:   m \"Decision: [what] because [why]\"",
                    "    Feature:    m \"Feature complete: [what]\"",
                    "    Fixed:      m \"Fixed: [what was wrong]\"",
                    "    Blocker:    m \"Blocker: [issue] need [solution]\"",
                    "    TIL:        m \"TIL: [what you learned]\"",
                    "    Insight:    m \"Insight: [observation]\"",
                    "",
                    "[bold cyan]WHEN TO RECORD[/bold cyan]",
                    "",
                    "  Natural breakpoints:",
                    "    ✓ After completing a logical unit of work",
                    "    ✓ Before switching to different task",
                    "    ✓ Before taking a break",
                    "    ✓ At end of work session",
                    "",
                    "  NOT during:",
                    "    ✗ Deep coding flow",
                    "    ✗ Middle of debugging",
                    "    ✗ Research phase",
                    "",
                    "[bold cyan]BATCH RECORDING[/bold cyan]",
                    "",
                    "  After a long session, record multiple items:",
                    "",
                    "    m \"Decision: Using FastAPI for the backend\"",
                    "    m \"Decision: PostgreSQL with SQLAlchemy ORM\"",
                    "    m \"Feature complete: user authentication\"",
                    "    m \"Feature complete: password reset flow\"",
                ],
            },
            # ============================================================
            # LESSON 6: Search and Retrieval
            # ============================================================
            {
                "id": "search",
                "title": "Search and Retrieval",
                "description": "Find information quickly in your memory",
                "content": [
                    "[bold cyan]BASIC SEARCH[/bold cyan]",
                    "",
                    "  Search timeline and modules:",
                    "    ms \"authentication\"",
                    "    ms \"database decision\"",
                    "",
                    "  Search with context (shows surrounding lines):",
                    "    ms \"auth\" --context 3",
                    "",
                    "[bold cyan]KNOWLEDGE BASE SEARCH[/bold cyan]",
                    "",
                    "  Search across ALL projects (requires KB setup):",
                    "    ms \"authentication\" --with-kb",
                    "",
                    "  Setup KB path first:",
                    "    python -m memory_tool config set kb.path /path/to/.memory",
                    "",
                    "[bold cyan]SEMANTIC SEARCH[/bold cyan]",
                    "",
                    "  Requires: pip install memory-tool[vector]",
                    "",
                    "  Search by meaning (not just keywords):",
                    "    ms --semantic \"how to handle user sessions\"",
                    "",
                    "  Hybrid (keyword + semantic):",
                    "    ms --hybrid \"authentication error handling\"",
                    "",
                    "[bold cyan]TIME-BASED VIEWING[/bold cyan]",
                    "",
                    "  View timeline entries:",
                    "    mtoday          # Today's entries",
                    "    mday 15         # Specific date (15th)",
                    "    mweek           # This week",
                    "    mmonth          # This month",
                    "    mdays 7         # Last 7 days",
                    "",
                    "  Edit timeline entries:",
                    "    medit           # Edit today's entries",
                    "    medit 15        # Edit specific date",
                    "",
                    "[bold cyan]INTERACTIVE BROWSER[/bold cyan]",
                    "",
                    "  Requires: pip install memory-tool[tui]",
                    "",
                    "  Launch interactive browser:",
                    "    mbrowse",
                    "",
                    "  Features:",
                    "    - Navigate timeline visually",
                    "    - Search with live results",
                    "    - View module structure",
                    "    - Keyboard shortcuts for navigation",
                    "",
                    "[bold cyan]TAG MANAGEMENT[/bold cyan]",
                    "",
                    "  [bold]List tags:[/bold]",
                    "    mtag                    # Timeline tags (default)",
                    "    mtag --all              # All file types",
                    "    mtag --type modules     # Specific type",
                    "    mtag --sort alpha       # Alphabetical order",
                    "",
                    "  [bold]Replace tags:[/bold]",
                    "    mtag replace oldtag newtag      # Rename tag",
                    "    mtag replace old new --dry-run  # Preview changes",
                    "",
                    "  [bold]Delete tags:[/bold]",
                    "    mtag delete testtag             # Remove tag",
                    "    mtag delete TAG --force         # Without confirmation",
                    "",
                    "  [bold]Find tags:[/bold]",
                    "    mtag find bug                   # Find all uses",
                    "",
                    "[bold cyan]CACHE MANAGEMENT[/bold cyan]",
                    "",
                    "  Search results are cached for performance:",
                    "    mcache                  # Show cache summary",
                    "    mcache --stats          # Detailed statistics",
                    "    mcache --clear          # Clear all cache",
                    "    mcache --clear-expired  # Clear expired only",
                    "",
                    "[bold cyan]ASK AI ABOUT YOUR MEMORY[/bold cyan]",
                    "",
                    "  Requires: pip install memory-tool[llm]",
                    "",
                    "  Configure LLM provider in .memory/config.yaml",
                    "  Then use RAG-powered Q&A:",
                    "",
                    "    mask \"What did I decide about the database?\"",
                    "    mask \"Summarize my work on authentication\"",
                    "    mask \"What blockers did I encounter last week?\"",
                ],
            },
            # ============================================================
            # LESSON 7: Modules
            # ============================================================
            {
                "id": "modules",
                "title": "Module Organization",
                "description": "Organize knowledge into modules",
                "content": [
                    "[bold cyan]WHAT ARE MODULES?[/bold cyan]",
                    "",
                    "  Modules organize knowledge by topic (space axis).",
                    "  Timeline captures events over time (time axis).",
                    "  Together: Time-Space Integrated Knowledge System",
                    "",
                    "  Module structure:",
                    "    .memory/modules/",
                    "    └── projects/",
                    "        └── my-project/",
                    "            ├── module.md       # Module definition",
                    "            ├── current.md      # Current status",
                    "            └── decisions.md    # Key decisions",
                    "",
                    "[bold cyan]CREATING MODULES[/bold cyan]",
                    "",
                    "  Create a new module:",
                    "    python -m memory_tool module create projects/my-project",
                    "",
                    "  Create a child module:",
                    "    python -m memory_tool module create projects/my-project/auth-system",
                    "",
                    "[bold cyan]MODULE FILES[/bold cyan]",
                    "",
                    "  [bold]module.md[/bold] - Module definition (rarely changes)",
                    "    - Name, description, purpose",
                    "    - Relationships to other modules",
                    "",
                    "  [bold]current.md[/bold] - Current status (updated frequently)",
                    "    - What's being worked on",
                    "    - Current state/progress",
                    "    - Related source files",
                    "",
                    "  [bold]decisions.md[/bold] - Key decisions (append-only)",
                    "    - Architecture decisions",
                    "    - Technology choices",
                    "    - Design rationales",
                    "",
                    "[bold cyan]VIEWING MODULES[/bold cyan]",
                    "",
                    "  List all modules:",
                    "    python -m memory_tool module list",
                    "",
                    "  View module tree:",
                    "    python -m memory_tool module tree",
                    "",
                    "  Validate module paths:",
                    "    mcheck",
                    "",
                    "[bold cyan]WHEN TO CREATE MODULES[/bold cyan]",
                    "",
                    "  Create new module when:",
                    "    ✓ Starting a new project",
                    "    ✓ New major feature (>500 lines expected)",
                    "    ✓ Independent concern with own lifecycle",
                    "",
                    "  DON'T create module for:",
                    "    ✗ Small enhancements (<100 lines)",
                    "    ✗ Temporary experiments",
                    "    ✗ Tightly coupled features",
                    "",
                    "[bold cyan]MODULE SPLIT GUIDELINES[/bold cyan]",
                    "",
                    "  Split when:",
                    "    - current.md > 300 lines",
                    "    - > 20 decisions in decisions.md",
                    "    - > 3 distinct topics",
                    "",
                    "  See full documentation:",
                    "    .memory/docs/MODULE-ORGANIZATION.md",
                ],
            },
            # ============================================================
            # LESSON 8: Quick Reference
            # ============================================================
            {
                "id": "quickref",
                "title": "Quick Reference Card",
                "description": "Essential commands at a glance",
                "content": [
                    "[bold cyan]RECORDING[/bold cyan]",
                    "  m \"message\"             Record to timeline",
                    "",
                    "[bold cyan]VIEWING[/bold cyan]",
                    "  mtoday                   Today's timeline",
                    "  mday DATE                Specific date",
                    "  mweek                    This week",
                    "  mmonth                   This month",
                    "  mdays N                  Last N days",
                    "  medit                    Edit timeline entries",
                    "",
                    "[bold cyan]SEARCHING[/bold cyan]",
                    "  ms \"query\"              Local search",
                    "  ms \"query\" --with-kb    Include knowledge base",
                    "  ms --semantic \"query\"   Semantic search",
                    "  ms --hybrid \"query\"     Keyword + semantic",
                    "",
                    "[bold cyan]TAG MANAGEMENT[/bold cyan]",
                    "  mtag                     List tags (default)",
                    "  mtag replace old new     Replace tag name",
                    "  mtag delete tag          Delete a tag",
                    "  mtag find tag            Find tag usage",
                    "",
                    "[bold cyan]CACHE MANAGEMENT[/bold cyan]",
                    "  mcache                   Cache summary",
                    "  mcache --clear           Clear all cache",
                    "",
                    "[bold cyan]AI INTEGRATION[/bold cyan]",
                    "  mcontext                 Build context for AI",
                    "  mcontext --with-map      Include code structure",
                    "  mask \"question\"          Ask AI about memory",
                    "",
                    "[bold cyan]MODULES[/bold cyan]",
                    "  mmodule list             List all modules",
                    "  mmodule tree             Show module tree",
                    "  mcheck                   Validate paths",
                    "",
                    "[bold cyan]PLANNING[/bold cyan]",
                    "  mplan create \"name\"      Create new plan",
                    "  mplan list               Show all plans",
                    "  mplan add \"name\" \"task\"  Add task to plan",
                    "  .memory/plans/recurring.md  Recurring items (shown in mplan daily)",
                    "",
                    "[bold cyan]SYSTEM[/bold cyan]",
                    "  mstatus                  Show statistics",
                    "  mupdate                  Check for updates",
                    "  mtutorial                Show this tutorial",
                    "  mhelp <command>          Detailed help",
                    "  malias list              Show aliases",
                    "",
                    "[bold cyan]KNOWLEDGE BASE[/bold cyan]",
                    "  mpublish <module>        Publish to KB",
                    "  mimport --list           Browse KB",
                    "  mimport <path>           Import from KB",
                    "",
                    "[bold cyan]NOTION (optional)[/bold cyan]",
                    "  nm \"message\"             Record to Notion",
                    "  nt                       Notion today",
                    "  nw                       Notion week",
                    "  nsync                    Sync with Notion",
                    "  nsync --timeline --sort  Sort local files by time",
                    "  nsync --timeline --reorder  Reorder Notion entries",
                    "  nwatch                   Auto-sync on file changes",
                    "    (singleton guard + cache auto-recovery)",
                ],
            },
        ]

    def _get_korean_lessons(self) -> List[Dict]:
        """Get Korean tutorial lessons."""
        return [
            # ============================================================
            # 레슨 1: 설치
            # ============================================================
            {
                "id": "installation",
                "title": "설치 및 초기 설정",
                "description": "memory_tool 설치하고 첫 프로젝트 설정하기",
                "content": [
                    "[bold cyan]단계 1: memory_tool 설치[/bold cyan]",
                    "",
                    "  방법 A - PyPI에서 설치 (권장):",
                    "    pip install memory-tool",
                    "",
                    "  방법 B - 소스에서 설치:",
                    "    git clone https://github.com/your-repo/memory_tool.git",
                    "    cd memory_tool",
                    "    pip install -e .",
                    "",
                    "  선택적 기능:",
                    "    pip install memory-tool[llm]     # LLM 연동 (mask, msummary)",
                    "    pip install memory-tool[vector]  # 시맨틱 검색",
                    "    pip install memory-tool[tui]     # 인터랙티브 브라우저 (mbrowse)",
                    "",
                    "[bold cyan]단계 2: 설치 확인[/bold cyan]",
                    "",
                    "  다음 명령어로 확인:",
                    "    python -m memory_tool --help     # 도움말 표시됨",
                    "    mhelp                            # 빠른 참조",
                    "",
                    "[bold cyan]단계 3: 프로젝트 초기화[/bold cyan]",
                    "",
                    "  프로젝트 디렉토리로 이동 후 실행:",
                    "    cd /path/to/your/project",
                    "    minit",
                    "",
                    "  생성되는 구조:",
                    "    .memory/           # 메모리 저장 디렉토리",
                    "    ├── timeline/      # 시간 기반 기록",
                    "    ├── modules/       # 모듈 기반 조직",
                    "    ├── config.yaml    # 설정 파일",
                    "    └── docs/          # 문서 템플릿",
                    "",
                    "    .claude/           # Claude Code 연동",
                    "    ├── skills/        # 메모리 툴 스킬",
                    "    └── guidelines.md  # 사용 가이드",
                    "",
                    "[bold cyan]단계 4: 명령어 별칭 설치[/bold cyan]",
                    "",
                    "  편리한 단축 명령어 (m, ms, 기, 검 등):",
                    "",
                    "  Windows PowerShell:",
                    "    malias install --powershell",
                    "    . $PROFILE                       # 프로필 다시 로드",
                    "",
                    "  Linux/macOS Bash:",
                    "    malias install --bash",
                    "    source ~/.bashrc                 # 프로필 다시 로드",
                    "",
                    "  Linux/macOS Zsh:",
                    "    malias install --zsh",
                    "    source ~/.zshrc                  # 프로필 다시 로드",
                    "",
                    "[bold yellow]다음:[/bold yellow] [bold]mtutorial setup --lang ko[/bold] 실행하여 CLAUDE.md 설정",
                ],
            },
            # ============================================================
            # 레슨 2: CLAUDE.md 설정
            # ============================================================
            {
                "id": "setup",
                "title": "CLAUDE.md 설정 (AI 연동)",
                "description": "Claude Code 및 다른 AI 도구와 연동하기 위한 프로젝트 설정",
                "content": [
                    "[bold cyan]CLAUDE.md가 왜 필요한가요?[/bold cyan]",
                    "",
                    "  CLAUDE.md는 AI 코딩 어시스턴트의 진입점입니다.",
                    "  Claude Code는 세션 시작 시 이 파일을 자동으로 읽습니다.",
                    "  다른 AI 도구 (Gemini CLI, ChatGPT)도 컨텍스트로 사용할 수 있습니다.",
                    "",
                    "[bold cyan]단계 1: CLAUDE.md 생성[/bold cyan]",
                    "",
                    "  템플릿을 프로젝트 루트로 복사:",
                    "",
                    "    # 템플릿 위치:",
                    "    .memory/templates/CLAUDE.md.template",
                    "",
                    "    # 프로젝트 루트로 복사:",
                    "    cp .memory/templates/CLAUDE.md.template CLAUDE.md",
                    "",
                    "[bold cyan]단계 2: CLAUDE.md 편집[/bold cyan]",
                    "",
                    "  최소 필수 내용:",
                    "",
                    "    ┌─────────────────────────────────────────────────────────┐",
                    "    │ # For Claude Code                                       │",
                    "    │                                                         │",
                    "    │ ## Context Files                                        │",
                    "    │                                                         │",
                    "    │ **Always read these files first:**                      │",
                    "    │ - `.claude/memory-context.md` - 현재 프로젝트 상태      │",
                    "    │ - `.claude/guidelines.md` - memory tool 사용 가이드     │",
                    "    │                                                         │",
                    "    │ ## Quick Commands                                       │",
                    "    │                                                         │",
                    "    │ ```bash                                                 │",
                    "    │ m \"메시지\"    # 타임라인에 기록                        │",
                    "    │ mcontext      # AI용 컨텍스트 생성                      │",
                    "    │ ms \"검색어\"   # 검색                                   │",
                    "    │ ```                                                     │",
                    "    │                                                         │",
                    "    │ **AI 세션 전에 `mcontext` 실행하세요.**                 │",
                    "    └─────────────────────────────────────────────────────────┘",
                    "",
                    "[bold cyan]단계 3: 프로젝트별 내용 추가[/bold cyan]",
                    "",
                    "  CLAUDE.md에 프로젝트 정보 추가:",
                    "",
                    "    ## Project Overview",
                    "    [프로젝트 목적 설명]",
                    "",
                    "    ## Technical Stack",
                    "    [기술 스택: Python 3.12, FastAPI, PostgreSQL 등]",
                    "",
                    "    ## Development Workflow",
                    "    [브랜치 전략, PR 프로세스 등]",
                    "",
                    "    ## Code Conventions",
                    "    [명명 규칙, 패턴 등]",
                    "",
                    "[bold cyan]단계 4: 컨텍스트 생성[/bold cyan]",
                    "",
                    "  mcontext 실행하여 컨텍스트 파일 생성:",
                    "    mcontext",
                    "",
                    "  생성 파일: .claude/memory-context.md",
                    "  (자동 생성됨, 수동 편집 금지)",
                    "",
                    "[bold cyan]단계 5: 설정 확인[/bold cyan]",
                    "",
                    "  다음 파일들이 존재하는지 확인:",
                    "    CLAUDE.md                    # 프로젝트 지침",
                    "    .claude/guidelines.md       # 메모리 툴 가이드",
                    "    .claude/memory-context.md   # 생성된 컨텍스트",
                    "",
                    "[bold yellow]중요:[/bold yellow]",
                    "  - 모든 AI 세션 전에 [bold]mcontext[/bold] 실행",
                    "  - CLAUDE.md는 AI가 읽기만 함 (지시를 따름)",
                    "  - memory-context.md는 자동 생성 (현재 상태 표시)",
                ],
            },
            # ============================================================
            # 레슨 3: 일상 워크플로우
            # ============================================================
            {
                "id": "daily",
                "title": "일상 워크플로우",
                "description": "매일 memory_tool을 사용하는 방법",
                "content": [
                    "[bold cyan]아침 루틴[/bold cyan]",
                    "",
                    "  1. AI 세션 시작 전 컨텍스트 업데이트:",
                    "     mcontext",
                    "",
                    "  2. 어제 작업 확인:",
                    "     mtoday   또는   오늘    # 오늘 타임라인",
                    "     mdays 2  또는   일수 2  # 최근 2일",
                    "",
                    "  3. AI 어시스턴트 시작:",
                    "     claude                  # Claude Code",
                    "     gemini                  # Gemini CLI",
                    "",
                    "[bold cyan]작업 중[/bold cyan]",
                    "",
                    "  [bold]자연스러운 중단점[/bold]에서 기록 - 집중 작업 중에는 X!",
                    "",
                    "  [bold green]기록하기 좋은 시점:[/bold green]",
                    "    ✓ 기능 완료 후",
                    "    ✓ 결정을 내린 후",
                    "    ✓ 버그 수정 후",
                    "    ✓ 휴식 전",
                    "",
                    "  [bold red]기록 피해야 할 시점:[/bold red]",
                    "    ✗ 코딩 플로우 중",
                    "    ✗ 작은 변경마다",
                    "    ✗ 사소한 질문/답변",
                    "",
                    "  [bold]기록 예시:[/bold]",
                    "",
                    "    기 \"기능 완료: JWT 인증 구현\"",
                    "    기 \"결정: PostgreSQL 사용 - 관계형 데이터, Redis 캐시\"",
                    "    기 \"수정: 워커 스레드 메모리 누수 - 풀 크기 제한\"",
                    "    기 \"블로커: API 속도 제한, 백오프 구현 필요\"",
                    "",
                    "    # 또는 영어 명령어:",
                    "    m \"Feature complete: user authentication with JWT\"",
                    "",
                    "[bold cyan]검색[/bold cyan]",
                    "",
                    "  로컬 검색 (현재 프로젝트):",
                    "    검 \"인증\"     또는    ms \"authentication\"",
                    "",
                    "  KB 포함 (전체 프로젝트):",
                    "    ms \"인증\" --with-kb",
                    "",
                    "[bold cyan]저녁 루틴[/bold cyan]",
                    "",
                    "  오늘 작업 리뷰:",
                    "    오늘    또는    mtoday",
                    "",
                    "  통계 확인:",
                    "    mstatus",
                    "",
                    "[bold yellow]핵심 원칙:[/bold yellow]",
                    "  \"0.5초에 캡처, 주말에 정리, 평생 사용\"",
                    "  너무 생각하지 말고 - 핵심만 기록하세요!",
                ],
            },
            # ============================================================
            # 레슨 4: AI 연동 (상세)
            # ============================================================
            {
                "id": "ai-integration",
                "title": "AI 도구 연동 (상세)",
                "description": "Claude Code, Gemini CLI 등 AI 도구 완벽 가이드",
                "content": [
                    "[bold cyan]개요[/bold cyan]",
                    "",
                    "  memory_tool은 AI 어시스턴트에 컨텍스트를 제공합니다:",
                    "  - 타임라인: 최근 작업 내용",
                    "  - 모듈: 지식 조직 구조",
                    "  - 플랜: 현재 진행 중인 작업",
                    "",
                    "  [bold]두 가지 사용 모드:[/bold]",
                    "  1. [bold]인터랙티브 모드[/bold] - AI CLI 직접 사용 (claude, gemini)",
                    "  2. [bold]헤드리스 모드[/bold] - mask 명령어로 빠른 Q&A",
                    "",
                    "-----------------------------------------------------------",
                    "[bold cyan]CLAUDE CODE & GEMINI CLI (동일한 사용법)[/bold cyan]",
                    "-----------------------------------------------------------",
                    "",
                    "  Claude Code와 Gemini CLI는 동일한 방식으로 작동합니다:",
                    "  - 둘 다 인터랙티브 모드 제공",
                    "  - 둘 다 헤드리스 모드 지원 (mask 명령어용)",
                    "  - 둘 다 컨텍스트 파일을 자동으로 읽음",
                    "",
                    "  [bold]설치:[/bold]",
                    "",
                    "    Claude Code:",
                    "      npm install -g @anthropic-ai/claude-code",
                    "",
                    "    Gemini CLI:",
                    "      npm install -g @anthropic-ai/gemini-cli",
                    "      # 또는: pip install google-genai",
                    "",
                    "-----------------------------------------------------------",
                    "[bold cyan]모드 1: 인터랙티브 모드[/bold cyan]",
                    "-----------------------------------------------------------",
                    "",
                    "  [bold]설정 (둘 다 동일):[/bold]",
                    "    1. 프로젝트 루트에 CLAUDE.md (또는 GEMINI.md)",
                    "    2. .claude/guidelines.md 존재",
                    "    3. 시작 전 mcontext 실행",
                    "",
                    "  [bold]워크플로우:[/bold]",
                    "",
                    "    # 1. 최신 컨텍스트 생성",
                    "    mcontext",
                    "",
                    "    # 2. 원하는 AI CLI 시작",
                    "    claude                          # Claude Code",
                    "    gemini                          # Gemini CLI",
                    "",
                    "    # 3. AI가 자동으로 읽는 파일:",
                    "    #    - CLAUDE.md / GEMINI.md (사용자 지시)",
                    "    #    - .claude/memory-context.md (현재 상태)",
                    "    #    - .claude/guidelines.md (메모리 툴 가이드)",
                    "",
                    "    # 4. 작업 완료 후 기록",
                    "    기 \"완료: 사용자 인증 구현\"",
                    "",
                    "  [bold]컨텍스트 옵션:[/bold]",
                    "",
                    "    mcontext                        # 기본 컨텍스트",
                    "    mcontext --with-map             # 코드 구조 포함",
                    "    mcontext --structure            # 파일 구조 포함",
                    "",
                    "-----------------------------------------------------------",
                    "[bold cyan]모드 2: 헤드리스 모드 (mask 명령어)[/bold cyan]",
                    "-----------------------------------------------------------",
                    "",
                    "  인터랙티브 모드 없이 빠른 Q&A에 AI 사용.",
                    "  Claude CLI와 Gemini CLI 모두 헤드리스 실행 지원.",
                    "",
                    "  [bold]단계 1: .memory/config.yaml에서 LLM 제공자 설정[/bold]",
                    "",
                    "    # Claude CLI 사용:",
                    "    llm:",
                    "      provider: claude-cli",
                    "      claude_cli:",
                    "        command: claude            # CLI 명령어",
                    "        model: null                # null = CLI 기본값 사용",
                    "",
                    "    # Gemini CLI 사용:",
                    "    llm:",
                    "      provider: gemini-cli",
                    "      gemini_cli:",
                    "        command: gemini            # CLI 명령어",
                    "        model: null                # null = CLI 기본값 사용",
                    "",
                    "  [bold]단계 2: mask 명령어 사용[/bold]",
                    "",
                    "    # 메모리에 대해 질문 (RAG 기반)",
                    "    질문 \"인증에 대해 어떤 결정을 했나요?\"",
                    "    질문 \"이번 주 작업 요약해줘\"",
                    "    질문 \"어떤 블로커가 있었나요?\"",
                    "",
                    "  [bold]mask 작동 방식:[/bold]",
                    "    1. 메모리에서 관련 컨텍스트 검색",
                    "    2. 컨텍스트로 프롬프트 구성",
                    "    3. 헤드리스 모드로 AI에 전송",
                    "    4. 답변 반환",
                    "",
                    "-----------------------------------------------------------",
                    "[bold cyan]기타 AI 도구 (ChatGPT, API 등)[/bold cyan]",
                    "-----------------------------------------------------------",
                    "",
                    "  CLI 연동이 없는 AI 도구:",
                    "",
                    "    # 1. 컨텍스트 생성",
                    "    mcontext",
                    "",
                    "    # 2. 컨텍스트 파일 내용 복사",
                    "    cat .claude/memory-context.md       # Linux/macOS",
                    "    type .claude\\memory-context.md     # Windows",
                    "",
                    "    # 3. AI 채팅에 컨텍스트로 붙여넣기",
                    "",
                    "  Anthropic/OpenAI API 사용:",
                    "",
                    "    llm:",
                    "      provider: anthropic",
                    "      anthropic:",
                    "        api_key: null              # 또는 ANTHROPIC_API_KEY 설정",
                    "        model: claude-3-5-sonnet-20241022",
                    "",
                    "[bold yellow]팁:[/bold yellow] AI에게 질문하기 전에 메모리 검색:",
                    "    검 \"인증\" --with-kb",
                    "    # 관련 검색 결과를 AI와 공유하면 더 좋은 답변",
                ],
            },
            # ============================================================
            # 레슨 5: 기록 모범 사례
            # ============================================================
            {
                "id": "recording",
                "title": "기록 모범 사례",
                "description": "무엇을, 언제, 어떻게 효과적으로 기록할까",
                "content": [
                    "[bold cyan]무엇을 기록할까[/bold cyan]",
                    "",
                    "  [bold green]✓ 기록해야 할 것:[/bold green]",
                    "",
                    "    결정:",
                    "      기 \"결정: 타입 안전성을 위해 TypeScript 사용\"",
                    "      기 \"결정: 관계형 데이터에 MongoDB 대신 PostgreSQL\"",
                    "",
                    "    완료:",
                    "      기 \"기능 완료: 이메일 인증 포함 사용자 등록\"",
                    "      기 \"리팩토링 완료: 인증 로직을 별도 모듈로 추출\"",
                    "",
                    "    버그 수정:",
                    "      기 \"수정: 동시 파일 업로드 경쟁 조건\"",
                    "      기 \"수정: 사용자 프로필 로딩 시 널 포인터\"",
                    "",
                    "    블로커/이슈:",
                    "      기 \"블로커: 서드파티 API 다운, 수정 대기 중\"",
                    "      기 \"이슈: 1000 사용자 이후 성능 저하\"",
                    "",
                    "    인사이트/학습:",
                    "      기 \"TIL: 대용량 데이터셋에 KEYS보다 Redis SCAN이 좋음\"",
                    "      기 \"인사이트: 배치 처리로 API 호출 80% 감소\"",
                    "",
                    "  [bold red]✗ 기록하지 말아야 할 것:[/bold red]",
                    "",
                    "    ✗ 사소한 변경: \"오타 수정\"",
                    "    ✗ 진행 중인 작업: \"인증 작업 중...\"",
                    "    ✗ 당연한 것: \"import 문 추가\"",
                    "    ✗ 모든 대화: \"Claude에게 X 물어봄\"",
                    "",
                    "[bold cyan]기록 형식[/bold cyan]",
                    "",
                    "  쉬운 검색을 위한 접두사 사용:",
                    "",
                    "    결정:     기 \"결정: [무엇] - [이유]\"",
                    "    기능:     기 \"기능 완료: [무엇]\"",
                    "    수정:     기 \"수정: [무엇이 잘못됐는지]\"",
                    "    블로커:   기 \"블로커: [이슈] - [필요한 해결책]\"",
                    "    TIL:      기 \"TIL: [배운 것]\"",
                    "    인사이트: 기 \"인사이트: [관찰]\"",
                    "",
                    "[bold cyan]언제 기록할까[/bold cyan]",
                    "",
                    "  자연스러운 중단점:",
                    "    ✓ 논리적 작업 단위 완료 후",
                    "    ✓ 다른 작업으로 전환 전",
                    "    ✓ 휴식 전",
                    "    ✓ 작업 세션 종료 시",
                    "",
                    "  기록하지 말 것:",
                    "    ✗ 깊은 코딩 플로우 중",
                    "    ✗ 디버깅 중간",
                    "    ✗ 리서치 단계",
                    "",
                    "[bold cyan]배치 기록[/bold cyan]",
                    "",
                    "  긴 세션 후 여러 항목 기록:",
                    "",
                    "    기 \"결정: 백엔드에 FastAPI 사용\"",
                    "    기 \"결정: SQLAlchemy ORM과 PostgreSQL\"",
                    "    기 \"기능 완료: 사용자 인증\"",
                    "    기 \"기능 완료: 비밀번호 재설정 플로우\"",
                ],
            },
            # ============================================================
            # 레슨 6: 검색
            # ============================================================
            {
                "id": "search",
                "title": "검색 및 조회",
                "description": "메모리에서 정보를 빠르게 찾기",
                "content": [
                    "[bold cyan]기본 검색[/bold cyan]",
                    "",
                    "  타임라인과 모듈 검색:",
                    "    검 \"인증\"",
                    "    ms \"database decision\"",
                    "",
                    "  컨텍스트 포함 검색 (주변 줄 표시):",
                    "    ms \"auth\" --context 3",
                    "",
                    "[bold cyan]지식 베이스 검색[/bold cyan]",
                    "",
                    "  모든 프로젝트 검색 (KB 설정 필요):",
                    "    ms \"인증\" --with-kb",
                    "",
                    "  먼저 KB 경로 설정:",
                    "    python -m memory_tool config set kb.path /path/to/.memory",
                    "",
                    "[bold cyan]시맨틱 검색[/bold cyan]",
                    "",
                    "  필요: pip install memory-tool[vector]",
                    "",
                    "  의미 기반 검색 (키워드뿐 아니라):",
                    "    ms --semantic \"사용자 세션 처리 방법\"",
                    "",
                    "  하이브리드 (키워드 + 시맨틱):",
                    "    ms --hybrid \"인증 에러 처리\"",
                    "",
                    "[bold cyan]시간 기반 조회[/bold cyan]",
                    "",
                    "  타임라인 항목 보기:",
                    "    오늘    또는   mtoday   # 오늘 항목",
                    "    날짜 15 또는   mday 15  # 특정 날짜",
                    "    주간    또는   mweek    # 이번 주",
                    "    월간    또는   mmonth   # 이번 달",
                    "    일수 7  또는   mdays 7  # 최근 7일",
                    "",
                    "  타임라인 항목 편집:",
                    "    medit                    # 오늘 항목 편집",
                    "    medit 15                 # 특정 날짜 편집",
                    "",
                    "[bold cyan]태그 관리[/bold cyan]",
                    "",
                    "  [bold]태그 목록:[/bold]",
                    "    mtag                    # 타임라인 태그 (기본값)",
                    "    mtag --all              # 모든 파일 타입",
                    "    mtag --type modules     # 특정 타입",
                    "    mtag --sort alpha       # 알파벳순",
                    "",
                    "  [bold]태그 치환:[/bold]",
                    "    mtag replace 기존태그 새태그     # 태그 이름 변경",
                    "    mtag replace old new --dry-run  # 변경 미리보기",
                    "",
                    "  [bold]태그 삭제:[/bold]",
                    "    mtag delete testtag             # 태그 제거",
                    "    mtag delete TAG --force         # 확인 없이 삭제",
                    "",
                    "  [bold]태그 찾기:[/bold]",
                    "    mtag find bug                   # 모든 사용 위치 찾기",
                    "",
                    "[bold cyan]캐시 관리[/bold cyan]",
                    "",
                    "  검색 결과가 성능 향상을 위해 캐시됩니다:",
                    "    mcache                  # 캐시 요약 표시",
                    "    mcache --stats          # 상세 통계",
                    "    mcache --clear          # 모든 캐시 삭제",
                    "    mcache --clear-expired  # 만료된 것만 삭제",
                    "",
                    "[bold cyan]인터랙티브 브라우저[/bold cyan]",
                    "",
                    "  필요: pip install memory-tool[tui]",
                    "",
                    "  인터랙티브 브라우저 실행:",
                    "    mbrowse",
                    "",
                    "  기능:",
                    "    - 타임라인 시각적 탐색",
                    "    - 실시간 검색 결과",
                    "    - 모듈 구조 보기",
                    "    - 키보드 단축키 네비게이션",
                    "",
                    "[bold cyan]AI에게 메모리 질문하기[/bold cyan]",
                    "",
                    "  필요: pip install memory-tool[llm]",
                    "",
                    "  .memory/config.yaml에서 LLM 제공자 설정",
                    "  그런 다음 RAG 기반 Q&A 사용:",
                    "",
                    "    질문 \"데이터베이스에 대해 뭘 결정했나요?\"",
                    "    질문 \"인증 작업 요약해줘\"",
                    "    질문 \"지난 주에 어떤 블로커가 있었나요?\"",
                    "    # 또는",
                    "    mask \"What did I decide about the database?\"",
                ],
            },
            # ============================================================
            # 레슨 7: 모듈
            # ============================================================
            {
                "id": "modules",
                "title": "모듈 조직",
                "description": "지식을 모듈로 조직하기",
                "content": [
                    "[bold cyan]모듈이란?[/bold cyan]",
                    "",
                    "  모듈은 주제별로 지식을 조직합니다 (공간축).",
                    "  타임라인은 시간에 따른 이벤트를 캡처합니다 (시간축).",
                    "  함께: 시간-공간 통합 지식 체계",
                    "",
                    "  모듈 구조:",
                    "    .memory/modules/",
                    "    └── projects/",
                    "        └── my-project/",
                    "            ├── module.md       # 모듈 정의",
                    "            ├── current.md      # 현재 상태",
                    "            └── decisions.md    # 주요 결정",
                    "",
                    "[bold cyan]모듈 생성[/bold cyan]",
                    "",
                    "  새 모듈 생성:",
                    "    python -m memory_tool module create projects/my-project",
                    "",
                    "  자식 모듈 생성:",
                    "    python -m memory_tool module create projects/my-project/auth-system",
                    "",
                    "[bold cyan]모듈 파일[/bold cyan]",
                    "",
                    "  [bold]module.md[/bold] - 모듈 정의 (거의 변경 안 함)",
                    "    - 이름, 설명, 목적",
                    "    - 다른 모듈과의 관계",
                    "",
                    "  [bold]current.md[/bold] - 현재 상태 (자주 업데이트)",
                    "    - 현재 작업 중인 것",
                    "    - 현재 상태/진행률",
                    "    - 관련 소스 파일",
                    "",
                    "  [bold]decisions.md[/bold] - 주요 결정 (추가만 함)",
                    "    - 아키텍처 결정",
                    "    - 기술 선택",
                    "    - 설계 근거",
                    "",
                    "[bold cyan]모듈 보기[/bold cyan]",
                    "",
                    "  모든 모듈 목록:",
                    "    python -m memory_tool module list",
                    "",
                    "  모듈 트리 보기:",
                    "    python -m memory_tool module tree",
                    "",
                    "  모듈 경로 검증:",
                    "    mcheck",
                    "",
                    "[bold cyan]언제 모듈 생성할까[/bold cyan]",
                    "",
                    "  새 모듈 생성 시점:",
                    "    ✓ 새 프로젝트 시작",
                    "    ✓ 새 주요 기능 (>500 라인 예상)",
                    "    ✓ 자체 라이프사이클을 가진 독립적 관심사",
                    "",
                    "  모듈 생성하지 말 것:",
                    "    ✗ 작은 개선 (<100 라인)",
                    "    ✗ 임시 실험",
                    "    ✗ 밀접하게 결합된 기능",
                    "",
                    "[bold cyan]모듈 분할 가이드라인[/bold cyan]",
                    "",
                    "  분할 시점:",
                    "    - current.md > 300 라인",
                    "    - decisions.md에 > 20 결정",
                    "    - > 3개의 구별되는 주제",
                    "",
                    "  전체 문서 보기:",
                    "    .memory/docs/MODULE-ORGANIZATION.md",
                ],
            },
            # ============================================================
            # 레슨 8: 한글 명령어
            # ============================================================
            {
                "id": "korean",
                "title": "한글 명령어",
                "description": "한글 단축키 사용법",
                "content": [
                    "[bold cyan]한글 별칭 설치[/bold cyan]",
                    "",
                    "  먼저 별칭 설치:",
                    "    malias install --powershell  # Windows",
                    "    malias install --bash        # Linux/macOS",
                    "",
                    "[bold cyan]로컬 메모리 명령어[/bold cyan]",
                    "",
                    "  기 \"메시지\"     # m - 기록",
                    "  검 \"검색어\"     # ms - 검색",
                    "  오늘             # mtoday - 오늘 타임라인",
                    "  주간             # mweek - 이번 주",
                    "  월간             # mmonth - 이번 달",
                    "  일수 N           # mdays - 최근 N일",
                    "  질문 \"질문\"     # mask - AI에게 질문",
                    "",
                    "[bold cyan]노션 명령어[/bold cyan]",
                    "",
                    "  노 \"메시지\"     # nm - 노션에 기록",
                    "  노검 \"검색어\"   # nsi - 노션 내 검색",
                    "  노오             # nt - 노션 오늘",
                    "  노주             # nw - 노션 주간",
                    "  노올 \"검색어\"   # ns - 노션 전체 검색",
                    "",
                    "[bold cyan]예시 워크플로우[/bold cyan]",
                    "",
                    "  # 아침",
                    "  오늘                     # 오늘 기록 확인",
                    "  mcontext                 # 컨텍스트 생성",
                    "",
                    "  # 작업 중",
                    "  기 \"인증 기능 완료\"    # 기록",
                    "  검 \"인증\"              # 검색",
                    "",
                    "  # 저녁",
                    "  오늘                     # 리뷰",
                    "  주간                     # 주간 리뷰",
                ],
            },
            # ============================================================
            # 레슨 9: 빠른 참조
            # ============================================================
            {
                "id": "quickref",
                "title": "빠른 참조 카드",
                "description": "핵심 명령어 한눈에 보기",
                "content": [
                    "[bold cyan]기록[/bold cyan]",
                    "  m \"message\"   /  기 \"메시지\"    타임라인에 기록",
                    "",
                    "[bold cyan]조회[/bold cyan]",
                    "  mtoday  /  오늘       오늘 타임라인",
                    "  mday DATE / 날짜 DATE 특정 날짜",
                    "  mweek   /  주간       이번 주",
                    "  mmonth  /  월간       이번 달",
                    "  mdays N /  일수 N     최근 N일",
                    "  medit                 타임라인 편집",
                    "",
                    "[bold cyan]검색[/bold cyan]",
                    "  ms \"query\"  /  검 \"검색어\"    로컬 검색",
                    "  ms \"query\" --with-kb            KB 포함",
                    "  ms --semantic \"query\"          시맨틱 검색",
                    "  ms --hybrid \"query\"            키워드+시맨틱",
                    "",
                    "[bold cyan]태그 관리[/bold cyan]",
                    "  mtag                             태그 목록 (기본)",
                    "  mtag replace 기존 신규           태그 치환",
                    "  mtag delete 태그                 태그 삭제",
                    "  mtag find 태그                   태그 찾기",
                    "",
                    "[bold cyan]캐시 관리[/bold cyan]",
                    "  mcache                           캐시 요약",
                    "  mcache --clear                   캐시 삭제",
                    "",
                    "[bold cyan]AI 연동[/bold cyan]",
                    "  mcontext                        AI용 컨텍스트",
                    "  mcontext --with-map             코드 구조 포함",
                    "  mask \"question\" / 질문 \"질문\"  AI에게 질문",
                    "",
                    "[bold cyan]모듈[/bold cyan]",
                    "  mmodule list                    모듈 목록",
                    "  mmodule tree                    모듈 트리",
                    "  mcheck                          경로 검증",
                    "",
                    "[bold cyan]플래닝[/bold cyan]",
                    "  mplan create \"name\"            플랜 생성",
                    "  mplan list                      플랜 목록",
                    "  mplan add \"name\" \"task\"       작업 추가",
                    "  .memory/plans/recurring.md      반복 항목 (mplan daily에 표시)",
                    "",
                    "[bold cyan]시스템[/bold cyan]",
                    "  mstatus                         통계",
                    "  mupdate                         업데이트 확인",
                    "  mtutorial                       튜토리얼",
                    "  mhelp <command>                 상세 도움말",
                    "  malias list                     별칭 목록",
                    "",
                    "[bold cyan]지식 베이스[/bold cyan]",
                    "  mpublish <module>               KB에 발행",
                    "  mimport --list                  KB 탐색",
                    "  mimport <path>                  KB에서 가져오기",
                    "",
                    "[bold cyan]노션 (선택)[/bold cyan]",
                    "  nm \"message\" / 노 \"메시지\"    노션에 기록",
                    "  nt / 노오                       노션 오늘",
                    "  nw / 노주                       노션 주간",
                    "  nsync                           노션 동기화",
                    "  nsync --timeline --sort         로컬 파일 시간순 정렬",
                    "  nsync --timeline --reorder      노션 항목 재정렬",
                    "  nwatch                          파일 변경 자동 동기화",
                    "    (중복 실행 방지 + 캐시 자동 복구)",
                ],
            },
        ]

    def run(self, lesson_id: str = None):
        """Run interactive tutorial.

        Args:
            lesson_id: Specific lesson ID to show, or None for menu
        """
        if lesson_id:
            # Show specific lesson
            lesson = next((l for l in self.lessons if l["id"] == lesson_id), None)
            if lesson:
                self._show_lesson(lesson)
            else:
                self.console.print(f"[red]ERROR[/red] Lesson not found: {lesson_id}")
                self.console.print("[dim]Use 'mtutorial --list' to see available lessons[/dim]")
        else:
            # Show menu
            self._show_menu()

    def _show_menu(self):
        """Show tutorial menu."""
        title = "Memory Tool 튜토리얼" if self.lang == "ko" else "Memory Tool Tutorial"
        subtitle = "memory_tool 명령어 사용법 학습" if self.lang == "ko" else "Learn how to use memory_tool commands"
        lang_hint = "[dim]English: mtutorial | 한국어: mtutorial --lang ko[/dim]"

        self.console.print(
            Panel.fit(
                f"[bold cyan]{title}[/bold cyan]\n\n{subtitle}\n\n{lang_hint}",
                border_style="cyan",
            )
        )
        self.console.print()

        # List lessons
        lessons_title = "사용 가능한 레슨:" if self.lang == "ko" else "Available Lessons:"
        self.console.print(f"[bold]{lessons_title}[/bold]\n")
        for i, lesson in enumerate(self.lessons, 1):
            self.console.print(f"  {i}. [cyan]{lesson['title']}[/cyan]")
            self.console.print(f"     {lesson['description']}")
            self.console.print()

        # Get user choice
        prompt = "[bold]레슨 선택 (1-{}) 또는 'q' 종료[/bold]".format(len(self.lessons)) if self.lang == "ko" else "[bold]Select a lesson (1-{}) or 'q' to quit[/bold]".format(len(self.lessons))
        choice = Prompt.ask(
            prompt,
            choices=[str(i) for i in range(1, len(self.lessons) + 1)] + ["q"],
            default="q",
        )

        if choice == "q":
            msg = "[yellow]튜토리얼 종료[/yellow]" if self.lang == "ko" else "[yellow]Tutorial closed[/yellow]"
            self.console.print(msg)
            return

        # Show selected lesson
        lesson_index = int(choice) - 1
        self._show_lesson(self.lessons[lesson_index])

        # Ask if user wants to see another lesson
        self.console.print()
        another_prompt = "[bold]다른 레슨 보기?[/bold]" if self.lang == "ko" else "[bold]View another lesson?[/bold]"
        if Prompt.ask(another_prompt, choices=["y", "n"], default="n") == "y":
            self._show_menu()

    def _show_lesson(self, lesson: Dict):
        """Show a single lesson.

        Args:
            lesson: Lesson dictionary
        """
        self.console.print()
        self.console.print(
            Panel.fit(
                f"[bold cyan]{lesson['title']}[/bold cyan]\n\n"
                f"{lesson['description']}",
                border_style="cyan",
            )
        )
        self.console.print()

        # Show content
        for line in lesson["content"]:
            self.console.print(line)

        self.console.print()

    def list_lessons(self):
        """List all available lessons."""
        title = "[bold cyan]사용 가능한 튜토리얼 레슨:[/bold cyan]" if self.lang == "ko" else "[bold cyan]Available Tutorial Lessons:[/bold cyan]"
        self.console.print(f"{title}\n")
        for lesson in self.lessons:
            self.console.print(f"  [cyan]{lesson['id']}[/cyan]: {lesson['title']}")
            self.console.print(f"    {lesson['description']}")
            self.console.print()
