/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MemoryToolPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian8 = require("obsidian");

// src/cli/memoryToolCli.ts
var import_obsidian = require("obsidian");
var execFn = null;
var execResolved = false;
function loadExec() {
  if (execResolved)
    return execFn;
  execResolved = true;
  if (import_obsidian.Platform.isMobile) {
    execFn = null;
    return null;
  }
  try {
    execFn = require("child_process").exec;
  } catch {
    execFn = null;
  }
  return execFn;
}
function escapeArg(value) {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/[\r\n]+/g, " ").trim();
}
function parseLastJsonObject(output) {
  const lines = output.split("\n").map((l) => l.trim()).filter((l) => l.startsWith("{"));
  for (let i = lines.length - 1; i >= 0; i--) {
    try {
      const data = JSON.parse(lines[i]);
      if (data && typeof data === "object")
        return data;
    } catch {
    }
  }
  return null;
}
var MemoryToolCli = class {
  constructor(pythonPath = "python", cwd = "") {
    this.pythonPath = pythonPath || "python";
    this.cwd = cwd || "";
  }
  setCwd(cwd) {
    this.cwd = cwd;
  }
  setPythonPath(path) {
    this.pythonPath = path || "python";
  }
  /**
   * Whether CLI-backed features can run at all.
   *
   * False on mobile, where there is no Python and no process to spawn. Callers
   * use this to hide features rather than to offer them and fail.
   */
  isAvailable() {
    return loadExec() !== null;
  }
  executeCommand(cmd, opts = {}) {
    return new Promise((resolve, reject) => {
      const exec = loadExec();
      if (!exec) {
        reject(
          new Error(
            "This feature needs the memory_tool CLI, which requires Python and is not available on mobile. Timeline capture works offline; run search, context and module commands on desktop."
          )
        );
        return;
      }
      const fullCmd = `${this.pythonPath} -m memory_tool ${cmd}`;
      const options = {
        // memory_tool prints Korean; without this Windows uses cp949 and mangles it.
        env: { ...process.env, PYTHONIOENCODING: "utf-8" },
        maxBuffer: opts.maxBuffer ?? 1024 * 1024 * 16
      };
      if (this.cwd)
        options.cwd = this.cwd;
      if (opts.timeout)
        options.timeout = opts.timeout;
      exec(fullCmd, options, (error, stdout, stderr) => {
        if (error) {
          const detail = (stderr || "").trim() || (stdout || "").trim();
          reject(new Error(detail || error.message));
        } else {
          resolve(stdout.trim());
        }
      });
    });
  }
  /** Record a timeline entry (m "message") */
  async recordTimeline(message) {
    const escapedMsg = message.replace(/"/g, '\\"');
    return this.executeCommand(`record "${escapedMsg}"`);
  }
  /**
   * Create a new module (`mmodule create`).
   *
   * `kind` and `nature` are passed straight through so memory_tool performs the
   * template assembly. It already resolves project templates over bundled ones,
   * splices the Nature outline into the body and substitutes placeholders --
   * duplicating that here would mean two template sources producing two
   * different documents for the same choice.
   */
  async createModule(name, description = "", tags = "", kind, nature, draft) {
    let cmd = `module create "${name}"`;
    if (description) {
      cmd += ` --desc "${escapeArg(description)}"`;
    }
    if (tags) {
      cmd += ` --tags "${escapeArg(tags)}"`;
    }
    if (kind) {
      cmd += ` --kind "${escapeArg(kind)}"`;
    }
    if (nature) {
      cmd += ` --nature "${escapeArg(nature)}"`;
    }
    if (draft) {
      cmd += " --draft";
    }
    return this.executeCommand(cmd);
  }
  /**
   * Append the skeleton sections a module does not have yet.
   *
   * The other half of `--draft`: a seed grows into the full document without
   * the author copying sections out of the template. memory_tool reads the kind
   * and nature from the module's own header, so neither is passed here.
   */
  async growModule(name) {
    return this.executeCommand(`module grow "${escapeArg(name)}"`);
  }
  /** Get list of active modules */
  async listModules() {
    try {
      const output = await this.executeCommand("module list");
      const lines = output.split("\n");
      const modules = [];
      for (const line of lines) {
        const trimmed = line.trim();
        if (trimmed.startsWith("- ")) {
          modules.push(trimmed.substring(2).trim());
        }
      }
      return modules;
    } catch {
      return [];
    }
  }
  /** Build AI Context (mcontext) */
  async buildContext() {
    return this.executeCommand("context");
  }
  /** Check module path health (mcheck) */
  async checkHealth() {
    return this.executeCommand("check");
  }
  /**
   * Bring the SQLite search index up to date.
   *
   * Needed because directly-written timeline entries bypass the indexing step
   * that `record` performs inline. The bare command indexes incrementally; the
   * `--force` full rebuild is deliberately not used, as it would make routine
   * reconciliation cost far more than the writes it is catching up on.
   */
  async syncIndex() {
    return this.executeCommand("index", { timeout: 12e4 });
  }
  /**
   * Ask a natural-language question about the knowledge base (mask).
   *
   * Uses --json so the answer arrives unwrapped: the human-facing output is
   * hard-wrapped to the terminal width, which inserts line breaks mid-sentence
   * and breaks Markdown rendering in a note.
   *
   * @param question Natural language question
   * @param opts simple: keyword RAG instead of the agent; provider: override;
   *             timeoutMs: how long to wait for the model
   */
  async ask(question, opts = {}) {
    const parts = [`ask "${escapeArg(question)}"`, "--json"];
    if (opts.simple)
      parts.push("--simple");
    if (opts.provider)
      parts.push(`--provider "${escapeArg(opts.provider)}"`);
    const output = await this.executeCommand(parts.join(" "), {
      timeout: opts.timeoutMs ?? 3e5
    });
    const data = parseLastJsonObject(output);
    if (!data) {
      throw new Error(`Could not parse the answer from memory_tool:
${output}`);
    }
    if (data.ok === false) {
      const providers = Array.isArray(data.available_providers) ? data.available_providers.join(", ") : "";
      throw new Error(
        String(data.error ?? "memory_tool reported a failure") + (providers ? ` (available providers: ${providers})` : "")
      );
    }
    return {
      question: String(data.question ?? question),
      answer: String(data.answer ?? ""),
      provider: String(data.provider ?? "unknown"),
      mode: String(data.mode ?? ""),
      tools: Array.isArray(data.tools) ? data.tools.map(String) : [],
      sources: Array.isArray(data.sources) ? data.sources.map(String) : []
    };
  }
  /**
   * Ask memory_tool where the knowledge base is, as absolute paths.
   *
   * Absolute paths matter: the base *name* is relative to the project root,
   * while Obsidian needs a path relative to the vault root. Those differ
   * whenever the vault is the base folder itself.
   */
  async getBaseInfo() {
    const output = await this.executeCommand("base show --json");
    const data = parseLastJsonObject(output);
    if (!data || typeof data.base !== "string" || typeof data.root !== "string") {
      throw new Error("memory_tool did not report a usable base folder");
    }
    return {
      root: data.root,
      base: data.base,
      baseName: data.base_name ?? "",
      source: data.source ?? "unknown",
      found: Boolean(data.found)
    };
  }
};

// src/modals/RecordModal.ts
var import_obsidian2 = require("obsidian");
var RecordModal = class extends import_obsidian2.Modal {
  constructor(app, record) {
    super(app);
    this.record = record;
  }
  onOpen() {
    const { contentEl, modalEl } = this;
    contentEl.empty();
    modalEl.addClass("memory-tool-quick-modal");
    const submitOnEnter = !import_obsidian2.Platform.isMobile;
    const input = contentEl.createEl("textarea", {
      cls: "memory-tool-quick-input",
      attr: {
        rows: submitOnEnter ? "1" : "3",
        placeholder: submitOnEnter ? "\uC9C0\uAE08 \uBB34\uC5C7\uC744 \uD558\uACE0 \uC788\uB098\uC694?  Enter\uB85C \uAE30\uB85D" : "\uC9C0\uAE08 \uBB34\uC5C7\uC744 \uD558\uACE0 \uC788\uB098\uC694?"
      }
    });
    input.focus();
    const row = contentEl.createDiv({ cls: "memory-tool-quick-actions" });
    const submitBtn = row.createEl("button", { cls: "mod-cta", text: "\uAE30\uB85D" });
    submitBtn.addEventListener("click", () => this.submit(input.value));
    input.addEventListener("keydown", (e) => {
      if (e.isComposing || e.keyCode === 229)
        return;
      if (submitOnEnter && e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.submit(input.value);
      }
    });
  }
  /**
   * Close first, then write.
   *
   * The write is fast enough that waiting would only add a visible pause, and a
   * failure still surfaces as a notice carrying the original text, so nothing is
   * lost by not blocking on it.
   */
  submit(raw) {
    const text = raw.trim();
    if (!text) {
      this.close();
      return;
    }
    this.close();
    this.record(text).catch((err) => {
      new import_obsidian2.Notice(`\uAE30\uB85D \uC2E4\uD328: ${err.message}
${text}`, 1e4);
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/modals/CreateModuleModal.ts
var import_obsidian3 = require("obsidian");

// src/paths.ts
var DEFAULT_BASE = ".memory";
function normalize(p) {
  return p.replace(/\\/g, "/").replace(/\/+$/, "");
}
function sameHost(a, b) {
  return a.toLowerCase() === b.toLowerCase();
}
function vaultRelativeBase(vaultRoot, absoluteBase) {
  const root = normalize(vaultRoot);
  const base = normalize(absoluteBase);
  if (!root || !base)
    return null;
  if (sameHost(root, base))
    return "";
  const withSep = root + "/";
  if (base.toLowerCase().startsWith(withSep.toLowerCase())) {
    return base.slice(withSep.length);
  }
  return null;
}
function normalizePrefix(value) {
  const trimmed = value.trim().replace(/\\/g, "/").replace(/^\.\//, "").replace(/\/+$/, "");
  if (trimmed === "" || trimmed === ".")
    return "";
  return trimmed;
}
function underBase(basePrefix, ...segments) {
  const parts = basePrefix ? [basePrefix, ...segments] : segments;
  return parts.filter((p) => p.length > 0).join("/");
}
function moduleCandidatePaths(basePrefix, moduleName) {
  const name = moduleName.replace(/\\/g, "/").replace(/\/{2,}/g, "/").replace(/^\/+|\/+$/g, "");
  const basename3 = name.split("/").pop() || name;
  return [
    underBase(basePrefix, "modules", name, `${basename3}.md`),
    underBase(basePrefix, "modules", `${name}.md`)
  ];
}
function underModules(basePrefix, vaultPath) {
  const path = normalize(vaultPath).replace(/^\/+/, "");
  const root = underBase(basePrefix, "modules");
  if (path.toLowerCase() === root.toLowerCase())
    return "";
  const withSep = root + "/";
  if (!path.toLowerCase().startsWith(withSep.toLowerCase()))
    return null;
  const rest = path.slice(withSep.length);
  if (rest.toLowerCase() === "archive" || rest.toLowerCase().startsWith("archive/")) {
    return null;
  }
  return rest;
}
function moduleNameFromPath(basePrefix, filePath) {
  const rest = underModules(basePrefix, filePath);
  if (!rest || !rest.toLowerCase().endsWith(".md"))
    return null;
  const segments = rest.slice(0, -3).split("/").filter((s) => s.length > 0);
  if (segments.length === 0)
    return null;
  const stem2 = segments[segments.length - 1];
  const parent = segments.length > 1 ? segments[segments.length - 2] : null;
  if (parent !== null && parent === stem2) {
    return segments.slice(0, -1).join("/");
  }
  return segments.join("/");
}
function modulePrefixFromFolder(basePrefix, folderPath) {
  return underModules(basePrefix, folderPath);
}
function describePrefix(basePrefix) {
  return basePrefix === "" ? "the vault root" : `${basePrefix}/`;
}

// src/moduleKinds.ts
var KINDS = [
  { id: "intent", answer: "\uC544\uC9C1 \uC5C6\uB2E4. \uC55E\uC73C\uB85C \uD558\uB824\uB294 \uAC83" },
  { id: "knowledge", answer: "\uC788\uB2E4. \uC9C0\uC2DD\uC774 \uD2C0\uB9B0 \uAC83" },
  { id: "implementation", answer: "\uC788\uB2E4. \uCF54\uB4DC\uB294 \uB9DE\uB294\uB370 \uBB38\uC11C\uB9CC \uB0A1\uC740 \uAC83" }
];
var KNOWLEDGE_NATURES = [
  {
    id: "concept",
    label: "concept (\uAC1C\uB150)",
    trigger: "\uB0B4 \uC774\uD574\uAC00 \uAE4A\uC5B4\uC9C8 \uB54C",
    answers: "\uC774\uAC8C \uBB54\uAC00?",
    lifetime: "\uBC18\uC601\uAD6C"
  },
  {
    id: "reference",
    label: "reference (\uB808\uD37C\uB7F0\uC2A4)",
    trigger: "\uB300\uC0C1\uC774 \uD328\uCE58\xB7\uAC1C\uC815\uB420 \uB54C",
    answers: "\uAC12\uC774 \uC5BC\uB9C8\uC778\uAC00?",
    lifetime: "\uBC84\uC804 \uC885\uC18D"
  },
  {
    id: "analysis",
    label: "analysis (\uBD84\uC11D)",
    trigger: "\uC0C8 \uC99D\uAC70\uAC00 \uB098\uC62C \uB54C",
    answers: "\uADF8\uB798\uC11C \uC5B4\uB5BB\uAC8C \uD310\uB2E8\uD558\uB098?",
    lifetime: "\uC218\uAC1C\uC6D4"
  },
  {
    id: "tracker",
    label: "tracker (\uCD94\uC801)",
    trigger: "\uC2DC\uAC04\uC774 \uD750\uB97C \uB54C",
    answers: "\uC9C0\uAE08 \uC0C1\uD0DC\uAC00 \uBB54\uAC00?",
    lifetime: "\uC218\uC77C~\uC218\uC8FC"
  },
  {
    id: "method",
    label: "method (\uBC29\uBC95\uB860)",
    trigger: "\uC801\uC6A9 \uD53C\uB4DC\uBC31\uC774 \uC62C \uB54C",
    answers: "\uC5B4\uB5BB\uAC8C \uD558\uB294\uAC00?",
    lifetime: "\uBC18\uC601\uAD6C"
  }
];
var INTENT_NATURES = [
  {
    id: "idea",
    label: "idea (\uCC29\uC0C1)",
    trigger: "\uC0C8 \uC790\uADF9\uC774 \uBD99\uC744 \uB54C",
    answers: "\uC774\uAC70 \uBB54\uAC00 \uB420\uAE4C?",
    lifetime: "\uB113\uD788\uAE30"
  },
  {
    id: "inquiry",
    label: "inquiry (\uB17C\uC758)",
    trigger: "\uB17C\uC758\uAC00 \uD55C \uBC14\uD034 \uB3CC \uB54C",
    answers: "\uBB34\uC5C7\uC744 \uACE8\uB77C\uC57C \uD558\uB098?",
    lifetime: "\uACE0\uB974\uAE30"
  },
  {
    id: "plan",
    label: "plan (\uC2E4\uD589 \uACC4\uD68D)",
    trigger: "\uD604\uC2E4\uC774 \uACC4\uD68D\uC744 \uC5B4\uAE38 \uB54C",
    answers: "\uBB34\uC5C7\uC744 \uC5B8\uC81C \uD558\uB294\uAC00?",
    lifetime: "\uC62E\uAE30\uAE30"
  }
];
var NATURES_BY_KIND = {
  knowledge: KNOWLEDGE_NATURES,
  implementation: [],
  intent: INTENT_NATURES
};

// src/modals/CreateModuleModal.ts
var CreateModuleModal = class extends import_obsidian3.Modal {
  constructor(app, cli, getBasePrefix, initialPath = "") {
    super(app);
    this.kind = "knowledge";
    this.nature = "concept";
    this.draft = false;
    this.cli = cli;
    this.getBasePrefix = getBasePrefix ?? (() => DEFAULT_BASE);
    this.initialPath = initialPath;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("memory-tool-record-modal");
    contentEl.createEl("h3", { text: "\uBAA8\uB4C8 \uC0DD\uC131" });
    const nameGroup = contentEl.createDiv({ cls: "memory-tool-form-group" });
    nameGroup.createEl("label", { text: "\uBAA8\uB4C8 \uACBD\uB85C" });
    const nameInput = nameGroup.createEl("input", {
      type: "text",
      placeholder: "\uC608: \uAC8C\uC784 \uBD84\uC11D/\uB2C8\uCF00/\uC804\uD22C \uACF5\uC2DD"
    });
    if (this.initialPath) {
      nameInput.value = `${this.initialPath}/`;
      nameGroup.createDiv({
        cls: "memory-tool-hint",
        text: `${this.initialPath}/ \uC544\uB798\uC5D0 \uB9CC\uB4ED\uB2C8\uB2E4.`
      });
    }
    nameInput.focus();
    nameInput.setSelectionRange(nameInput.value.length, nameInput.value.length);
    const descGroup = contentEl.createDiv({ cls: "memory-tool-form-group" });
    descGroup.createEl("label", { text: "\uBAA9\uC801 (\uD55C \uBB38\uC7A5)" });
    const descInput = descGroup.createEl("input", {
      type: "text",
      placeholder: "\uB450 \uBB38\uC7A5\uC774 \uB118\uC5B4\uAC00\uBA74 \uBAA8\uB4C8\uC744 \uBD84\uB9AC\uD558\uB77C\uB294 \uC2E0\uD638\uC785\uB2C8\uB2E4"
    });
    const tagsGroup = contentEl.createDiv({ cls: "memory-tool-form-group" });
    tagsGroup.createEl("label", { text: "\uD0DC\uADF8 (\uC27C\uD45C \uAD6C\uBD84, \uC120\uD0DD)" });
    const tagsInput = tagsGroup.createEl("input", {
      type: "text",
      placeholder: "\uC608: search, python, cli"
    });
    const kindGroup = contentEl.createDiv({ cls: "memory-tool-form-group" });
    kindGroup.createEl("label", {
      text: "Kind \u2014 \uC774 \uBB38\uC11C\uAC00 \uC11C\uC220\uD558\uB294 \uB300\uC0C1\uC774 \uC774\uBBF8 \uC874\uC7AC\uD558\uB294\uAC00?"
    });
    const kindSelect = kindGroup.createEl("select");
    for (const k of KINDS) {
      kindSelect.createEl("option", { value: k.id, text: `${k.answer} \u2192 ${k.id}` });
    }
    kindSelect.value = this.kind;
    const natureGroup = contentEl.createDiv({ cls: "memory-tool-form-group" });
    natureGroup.createEl("label", { text: "Nature \u2014 \uBB34\uC5C7\uC774 \uC774 \uBAA8\uB4C8\uC744 \uAC31\uC2E0\uC2DC\uD0A4\uB294\uAC00?" });
    const natureSelect = natureGroup.createEl("select");
    const natureHint = natureGroup.createDiv({ cls: "memory-tool-hint" });
    const syncNatureHint = () => {
      const chosen = NATURES_BY_KIND[this.kind].find(
        (n) => n.id === natureSelect.value
      );
      natureHint.setText(chosen ? `\uB2F5\uD558\uB294 \uC9C8\uBB38: ${chosen.answers}` : "");
    };
    const syncNatureOptions = () => {
      const options = NATURES_BY_KIND[this.kind];
      natureSelect.empty();
      natureGroup.toggleClass("memory-tool-hidden", options.length === 0);
      for (const n of options) {
        natureSelect.createEl("option", {
          value: n.id,
          text: `${n.trigger} \u2192 ${n.label} \xB7 ${n.lifetime}`
        });
      }
      this.nature = options.length ? options[0].id : void 0;
      if (options.length) {
        natureSelect.value = options[0].id;
      }
      syncNatureHint();
    };
    syncNatureOptions();
    natureSelect.addEventListener("change", () => {
      this.nature = natureSelect.value;
      syncNatureHint();
    });
    kindSelect.addEventListener("change", () => {
      this.kind = kindSelect.value;
      syncNatureOptions();
    });
    const draftGroup = contentEl.createDiv({ cls: "memory-tool-form-group" });
    const draftLabel = draftGroup.createEl("label");
    const draftToggle = draftLabel.createEl("input", { type: "checkbox" });
    draftLabel.appendText(" \uCD08\uC548\uC73C\uB85C \uC2DC\uC791 (--draft)");
    draftGroup.createDiv({
      cls: "memory-tool-hint",
      text: "\uC804\uCCB4 \uACE8\uACA9 \uB300\uC2E0 40\uC904\uC9DC\uB9AC \uC528\uC557 \uBB38\uC11C\uB97C \uB9CC\uB4ED\uB2C8\uB2E4. \uD544\uC694\uD574\uC9C0\uBA74 'mmodule grow' \uB85C \uB098\uBA38\uC9C0 \uC808\uC744 \uBD99\uC785\uB2C8\uB2E4."
    });
    draftToggle.addEventListener("change", () => {
      this.draft = draftToggle.checked;
    });
    const buttonsEl = contentEl.createDiv({ cls: "memory-tool-modal-buttons" });
    const cancelBtn = buttonsEl.createEl("button", { text: "\uCDE8\uC18C" });
    const submitBtn = buttonsEl.createEl("button", { text: "\uC0DD\uC131", cls: "mod-cta" });
    cancelBtn.addEventListener("click", () => this.close());
    submitBtn.addEventListener("click", async () => {
      const name = nameInput.value.trim();
      if (!name) {
        new import_obsidian3.Notice("\uBAA8\uB4C8 \uACBD\uB85C\uB97C \uC785\uB825\uD558\uC138\uC694.");
        return;
      }
      submitBtn.setAttr("disabled", "true");
      try {
        await this.create(name, descInput.value.trim(), tagsInput.value.trim());
        this.close();
      } catch (err) {
        new import_obsidian3.Notice(`\uBAA8\uB4C8 \uC0DD\uC131 \uC2E4\uD328: ${err.message}`);
        submitBtn.removeAttribute("disabled");
      }
    });
  }
  async create(name, description, tags) {
    await this.cli.createModule(
      name,
      description,
      tags,
      this.kind,
      this.nature,
      this.draft
    );
    const basePrefix = this.getBasePrefix();
    const candidates = moduleCandidatePaths(basePrefix, name);
    const path = await this.waitForFile(candidates);
    if (!path) {
      new import_obsidian3.Notice(
        `\uBAA8\uB4C8\uC740 \uC0DD\uC131\uB410\uC9C0\uB9CC vault\uC5D0\uC11C \uC5F4\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4. \uD655\uC778\uD55C \uACBD\uB85C: ${candidates.join(", ")}`,
        8e3
      );
      return;
    }
    await this.openPath(path);
    const base = this.nature ? `${this.kind} / ${this.nature}` : this.kind;
    const label = this.draft ? `${base} (draft)` : base;
    new import_obsidian3.Notice(`\uBAA8\uB4C8 \uC0DD\uC131: ${name} (${label})`);
  }
  /**
   * Wait for the file memory_tool just wrote to become visible.
   *
   * It is created outside Obsidian, so both the adapter and the file index can
   * lag by a moment; polling briefly beats failing on the first miss.
   */
  async waitForFile(candidates) {
    for (let i = 0; i < 15; i++) {
      for (const path of candidates) {
        if (await this.app.vault.adapter.exists(path))
          return path;
      }
      await new Promise((resolve) => window.setTimeout(resolve, 100));
    }
    return null;
  }
  async openPath(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file instanceof import_obsidian3.TFile) {
      await this.app.workspace.getLeaf(false).openFile(file);
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/modals/ModuleSuggestModal.ts
var import_obsidian4 = require("obsidian");
var ModuleSuggestModal = class extends import_obsidian4.FuzzySuggestModal {
  constructor(app, lister, getBasePrefix, onChoose) {
    super(app);
    this.modules = [];
    this.lister = lister;
    this.getBasePrefix = getBasePrefix ?? (() => DEFAULT_BASE);
    this.onChoose = onChoose ?? null;
    this.setPlaceholder("Type to search active memory_tool modules...");
  }
  async onOpen() {
    super.onOpen();
    this.modules = await this.lister();
  }
  getItems() {
    return this.modules;
  }
  getItemText(item) {
    return item;
  }
  onChooseItem(item, evt) {
    if (this.onChoose) {
      this.onChoose(item);
      return;
    }
    const possiblePaths = moduleCandidatePaths(this.getBasePrefix(), item);
    let foundFile = null;
    for (const p of possiblePaths) {
      const abstractFile = this.app.vault.getAbstractFileByPath(p);
      if (abstractFile instanceof import_obsidian4.TFile) {
        foundFile = abstractFile;
        break;
      }
    }
    if (foundFile) {
      this.app.workspace.getLeaf(false).openFile(foundFile);
      return;
    }
    new import_obsidian4.Notice(
      `Could not find '${item}' in this vault. Looked in: ${possiblePaths.join(", ")}. Check the Knowledge Base Folder setting.`,
      8e3
    );
  }
};

// src/modals/AskModal.ts
var import_obsidian5 = require("obsidian");
var AskModal = class extends import_obsidian5.Modal {
  constructor(app, cli, getBasePrefix) {
    super(app);
    this.running = false;
    this.lastResult = null;
    /**
     * Owns the lifecycle of rendered Markdown. MarkdownRenderer attaches child
     * components (embeds, code blocks) that must be unloaded with the modal;
     * Modal is not itself a Component, so it cannot serve as that owner.
     */
    this.renderHost = new import_obsidian5.Component();
    /** Keyword RAG instead of the tool-using agent: faster, less thorough. */
    this.simpleMode = false;
    this.cli = cli;
    this.getBasePrefix = getBasePrefix ?? (() => "");
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("memory-tool-ask-modal");
    this.renderHost.load();
    contentEl.createEl("h3", { text: "\u{1F914} Ask Your Memory (mask)" });
    this.inputEl = contentEl.createEl("textarea", {
      cls: "memory-tool-input-textarea",
      placeholder: "Ask about your knowledge base... e.g. \uC5B4\uC81C \uBB34\uC2A8 \uC791\uC5C5\uC744 \uD588\uB098\uC694? (Ctrl+Enter to ask)"
    });
    this.inputEl.focus();
    new import_obsidian5.Setting(contentEl).setName("Fast mode").setDesc(
      "Keyword search instead of the tool-using agent. Quicker, but it cannot follow up on what it finds."
    ).addToggle(
      (toggle) => toggle.setValue(this.simpleMode).onChange((value) => {
        this.simpleMode = value;
      })
    );
    const buttonsEl = contentEl.createDiv({ cls: "memory-tool-modal-buttons" });
    const closeBtn = buttonsEl.createEl("button", { text: "Close" });
    closeBtn.addEventListener("click", () => this.close());
    this.insertBtn = buttonsEl.createEl("button", { text: "Insert into note" });
    this.insertBtn.disabled = true;
    this.insertBtn.addEventListener("click", () => this.insertIntoNote());
    this.submitBtn = buttonsEl.createEl("button", {
      text: "Ask",
      cls: "mod-cta"
    });
    this.submitBtn.addEventListener("click", () => this.run());
    this.statusEl = contentEl.createDiv({ cls: "memory-tool-ask-status" });
    this.answerEl = contentEl.createDiv({ cls: "memory-tool-ask-answer" });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
        e.preventDefault();
        this.run();
      }
    });
  }
  async run() {
    if (this.running)
      return;
    const question = this.inputEl.value.trim();
    if (!question) {
      new import_obsidian5.Notice("Please enter a question.");
      return;
    }
    this.running = true;
    this.submitBtn.disabled = true;
    this.submitBtn.setText("Thinking...");
    this.insertBtn.disabled = true;
    this.answerEl.empty();
    const started = Date.now();
    this.statusEl.setText("Searching memory and asking the model...");
    const ticker = window.setInterval(() => {
      const seconds = Math.floor((Date.now() - started) / 1e3);
      this.statusEl.setText(`Searching memory and asking the model... ${seconds}s`);
    }, 1e3);
    try {
      const result = await this.cli.ask(question, { simple: this.simpleMode });
      this.lastResult = result;
      await this.renderAnswer(result, Date.now() - started);
      this.insertBtn.disabled = false;
    } catch (err) {
      this.lastResult = null;
      this.statusEl.setText("");
      this.answerEl.empty();
      this.answerEl.createEl("p", {
        text: `Failed to answer: ${err.message}`,
        cls: "memory-tool-ask-error"
      });
    } finally {
      window.clearInterval(ticker);
      this.running = false;
      this.submitBtn.disabled = false;
      this.submitBtn.setText("Ask");
    }
  }
  async renderAnswer(result, elapsedMs) {
    const seconds = (elapsedMs / 1e3).toFixed(1);
    const modeLabel = result.mode === "simple" ? "fast" : "agent";
    this.statusEl.setText(`${result.provider} \xB7 ${modeLabel} \xB7 ${seconds}s`);
    this.answerEl.empty();
    await import_obsidian5.MarkdownRenderer.render(
      this.app,
      result.answer || "_(empty answer)_",
      this.answerEl,
      "",
      this.renderHost
    );
    if (result.tools.length) {
      this.answerEl.createEl("p", {
        text: `Tools used: ${result.tools.join(", ")}`,
        cls: "memory-tool-ask-meta"
      });
    }
    if (result.sources.length) {
      const details = this.answerEl.createEl("details", {
        cls: "memory-tool-ask-sources"
      });
      details.createEl("summary", { text: `Sources (${result.sources.length})` });
      const list = details.createEl("ul");
      for (const source of result.sources) {
        const item = list.createEl("li");
        const vaultPath = this.toVaultPath(source);
        const file = vaultPath ? this.app.vault.getAbstractFileByPath(vaultPath) : null;
        if (file instanceof import_obsidian5.TFile) {
          const link = item.createEl("a", { text: vaultPath, href: "#" });
          link.addEventListener("click", (e) => {
            e.preventDefault();
            this.app.workspace.getLeaf(false).openFile(file);
            this.close();
          });
        } else {
          item.setText(source);
        }
      }
    }
  }
  /**
   * Convert a memory_tool source path into a vault-relative path.
   *
   * memory_tool reports paths relative to the *project root* (for example
   * ".memory/timeline/..."), while the vault root may be the base folder
   * itself. Re-anchoring through the base prefix keeps links working in both
   * layouts.
   */
  toVaultPath(source) {
    const normalized = source.replace(/\\/g, "/").replace(/^\.\//, "");
    if (!normalized)
      return null;
    const prefix = this.getBasePrefix();
    if (this.app.vault.getAbstractFileByPath(normalized))
      return normalized;
    const segments = normalized.split("/");
    if (segments.length > 1) {
      const withoutBase = segments.slice(1).join("/");
      const candidate = underBase(prefix, withoutBase);
      if (this.app.vault.getAbstractFileByPath(candidate))
        return candidate;
    }
    return null;
  }
  /** Append the question and answer to the active note. */
  async insertIntoNote() {
    if (!this.lastResult)
      return;
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian5.Notice("Open a note first, then insert the answer.");
      return;
    }
    const { question, answer, provider, mode } = this.lastResult;
    const block = `
> [!question] ${question}
> _memory_tool \xB7 ${provider} \xB7 ${mode}_

${answer}
`;
    try {
      await this.app.vault.append(file, block);
      new import_obsidian5.Notice(`Answer appended to ${file.basename}`);
    } catch (err) {
      new import_obsidian5.Notice(`Could not insert the answer: ${err.message}`);
    }
  }
  onClose() {
    this.renderHost.unload();
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/views/MemoryPanelView.ts
var import_obsidian6 = require("obsidian");

// src/timeline/format.ts
var DEFAULT_FILENAME_LAYOUT = "day";
var DEFAULT_TAG_FORMAT = "bracket";
var DATE_FILE = /^\d{4}-\d{2}-\d{2}\.md$/;
var DAY_FILE = /^\d{1,2}\.md$/;
var MONTH_DIR = /^\d{4}-\d{2}$/;
var DEFAULT_TIMELINE_CONFIG = {
  filenameLayout: DEFAULT_FILENAME_LAYOUT,
  tagFormat: DEFAULT_TAG_FORMAT
};
function pad(n) {
  return n < 10 ? `0${n}` : String(n);
}
function isoDate(d) {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}
function yearMonth(d) {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}`;
}
function hourMinute(d) {
  return `${pad(d.getHours())}:${pad(d.getMinutes())}`;
}
function filenameFor(date, layout) {
  return layout === "date" ? `${isoDate(date)}.md` : `${pad(date.getDate())}.md`;
}
function headerFor(date) {
  return `# ${isoDate(date)} Timeline`;
}
function candidatePaths(basePrefix, date) {
  const paths = [];
  for (const dir of timelineMonthDirs(basePrefix, date)) {
    for (const layout of ["date", "day"]) {
      paths.push(`${dir}/${filenameFor(date, layout)}`);
    }
  }
  return paths;
}
function timelineDir(basePrefix, date) {
  return underBase(basePrefix, "timeline", "daily", yearMonth(date));
}
function timelineMonthDirs(basePrefix, date) {
  const ym = yearMonth(date);
  return [
    underBase(basePrefix, "timeline", "daily", ym),
    underBase(basePrefix, "timeline", ym)
  ];
}
function timelineRootDirs(basePrefix) {
  return [underBase(basePrefix, "timeline", "daily"), underBase(basePrefix, "timeline")];
}
function sortMonthDirs(names) {
  return names.filter((n) => MONTH_DIR.test(n)).sort().reverse();
}
function layoutFromFilenames(names) {
  let date = 0;
  let day = 0;
  for (const name of names) {
    if (DATE_FILE.test(name))
      date += 1;
    else if (DAY_FILE.test(name))
      day += 1;
  }
  if (date === 0 && day === 0)
    return null;
  return day > date ? "day" : "date";
}
function formatEntry(date, message, tags = [], tagFormat = DEFAULT_TAG_FORMAT) {
  const time = hourMinute(date);
  const clean = tags.map((t) => t.trim()).filter((t) => t.length > 0);
  if (clean.length === 0)
    return `- ${time} | ${message}`;
  if (tagFormat === "hashtag") {
    const tagStr2 = clean.map((t) => `#${t.replace(/ /g, "-")}`).join(" ");
    return `- ${time} | ${message} ${tagStr2}`;
  }
  const tagStr = clean.map((t) => `[${t.replace(/ /g, "-")}]`).join(" ");
  return `- ${time} | ${tagStr} ${message}`;
}
function sanitizeMessage(message) {
  return message.replace(/[\r\n]+/g, " ").trim();
}
function appendEntry(existing, entry) {
  return `${existing.replace(/\n+$/, "")}
${entry}
`;
}
function newFileBody(date, entry) {
  return `${headerFor(date)}
${entry}
`;
}
function configuredFilenameLayout(parsed) {
  const layout = (parsed ?? {})?.timeline?.filename;
  return layout === "date" || layout === "day" ? layout : null;
}
function timelineConfigFrom(parsed) {
  const root = parsed ?? {};
  const tagFmt = root?.tag?.storage_format;
  return {
    filenameLayout: configuredFilenameLayout(parsed) ?? DEFAULT_FILENAME_LAYOUT,
    tagFormat: tagFmt === "hashtag" || tagFmt === "bracket" ? tagFmt : DEFAULT_TAG_FORMAT
  };
}

// src/views/MemoryPanelView.ts
var MEMORY_PANEL_VIEW = "memory-tool-panel";
var MemoryPanelView = class extends import_obsidian6.ItemView {
  constructor(leaf, host) {
    super(leaf);
    /** Module list cache. null until something asks for it. */
    this.modules = null;
    /** Guards against a second load while the first is in flight. */
    this.loadingModules = false;
    this.host = host;
  }
  getViewType() {
    return MEMORY_PANEL_VIEW;
  }
  getDisplayText() {
    return "Memory Tool";
  }
  getIcon() {
    return "clock";
  }
  async onOpen() {
    this.addAction("pencil", "\uC785\uB825\uCC3D\uC73C\uB85C \uC774\uB3D9", () => this.focusCapture());
    this.addAction("refresh-cw", "\uC0C8\uB85C \uACE0\uCE68", () => {
      void this.refreshToday();
      void this.reloadModules();
    });
    const root = this.contentEl;
    root.empty();
    root.addClass("memory-tool-panel");
    this.buildCapture(root);
    this.buildToday(root);
    this.buildModules(root);
    this.buildActions(root);
    await this.refreshToday();
    void this.renderModules();
  }
  async onClose() {
    this.contentEl.empty();
  }
  /** Focus the capture box; used by the "capture" command. */
  focusCapture() {
    this.captureInput?.focus();
  }
  // --- Capture -------------------------------------------------------------
  buildCapture(root) {
    const section = root.createDiv({ cls: "memory-tool-capture" });
    const submitOnEnter = !import_obsidian6.Platform.isMobile;
    this.captureInput = section.createEl("textarea", {
      cls: "memory-tool-capture-input",
      attr: {
        rows: submitOnEnter ? "2" : "3",
        placeholder: submitOnEnter ? "\uC9C0\uAE08 \uBB34\uC5C7\uC744 \uD558\uACE0 \uC788\uB098\uC694?  Enter\uB85C \uAE30\uB85D, Shift+Enter \uC904\uBC14\uAFC8" : "\uC9C0\uAE08 \uBB34\uC5C7\uC744 \uD558\uACE0 \uC788\uB098\uC694?"
      }
    });
    const row = section.createDiv({ cls: "memory-tool-capture-row" });
    this.statusEl = row.createDiv({ cls: "memory-tool-capture-status" });
    const submitBtn = row.createEl("button", {
      cls: "mod-cta memory-tool-capture-send",
      text: "\uAE30\uB85D"
    });
    submitBtn.addEventListener("click", () => void this.submitCapture());
    this.captureInput.addEventListener("keydown", (e) => {
      if (e.isComposing || e.keyCode === 229)
        return;
      if (submitOnEnter && e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        void this.submitCapture();
      }
    });
  }
  async submitCapture() {
    const text = this.captureInput.value.trim();
    if (!text)
      return;
    this.captureInput.value = "";
    try {
      const result = await this.host.recordEntry(text);
      this.setStatus(`\uAE30\uB85D\uB428 \xB7 ${result.entry.slice(0, 60)}`, false);
      await this.refreshToday();
    } catch (err) {
      this.captureInput.value = text;
      this.setStatus(`\uAE30\uB85D \uC2E4\uD328: ${err.message}`, true);
    }
  }
  setStatus(text, isError) {
    this.statusEl.setText(text);
    this.statusEl.toggleClass("memory-tool-status-error", isError);
  }
  // --- Today ---------------------------------------------------------------
  buildToday(root) {
    const details = root.createEl("details", { cls: "memory-tool-section" });
    details.setAttr("open", "");
    const summary = details.createEl("summary");
    summary.createSpan({ text: "\uC624\uB298 \uD0C0\uC784\uB77C\uC778" });
    const refresh = summary.createSpan({ cls: "memory-tool-section-action" });
    (0, import_obsidian6.setIcon)(refresh, "refresh-cw");
    refresh.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      void this.refreshToday();
    });
    this.todayList = details.createDiv({ cls: "memory-tool-today" });
  }
  /**
   * Show today's entries, newest last (the file's own order).
   *
   * Reads through the adapter and checks every known filename layout, so the
   * panel keeps working on a knowledge base that predates the current setting.
   */
  async refreshToday() {
    this.todayList.empty();
    const adapter = this.app.vault.adapter;
    let content = null;
    let found = null;
    for (const path of candidatePaths(this.host.basePrefix, new Date())) {
      if (await adapter.exists(path)) {
        content = await adapter.read(path);
        found = path;
        break;
      }
    }
    if (content === null) {
      this.todayList.createDiv({
        cls: "memory-tool-empty",
        text: "\uC624\uB298 \uAE30\uB85D\uC774 \uC544\uC9C1 \uC5C6\uC2B5\uB2C8\uB2E4."
      });
      return;
    }
    const entries = content.split("\n").map((l) => l.trim()).filter((l) => l.startsWith("- "));
    if (entries.length === 0) {
      this.todayList.createDiv({ cls: "memory-tool-empty", text: "\uC624\uB298 \uAE30\uB85D\uC774 \uC544\uC9C1 \uC5C6\uC2B5\uB2C8\uB2E4." });
      return;
    }
    for (const entry of entries) {
      const row = this.todayList.createDiv({ cls: "memory-tool-entry" });
      const body = entry.slice(2);
      const split = body.indexOf(" | ");
      if (split > 0) {
        row.createSpan({ cls: "memory-tool-entry-time", text: body.slice(0, split) });
        row.createSpan({ cls: "memory-tool-entry-text", text: body.slice(split + 3) });
      } else {
        row.createSpan({ cls: "memory-tool-entry-text", text: body });
      }
    }
    if (found) {
      const open = this.todayList.createDiv({
        cls: "memory-tool-open-file",
        text: "\uD30C\uC77C \uC5F4\uAE30"
      });
      open.addEventListener("click", () => void this.openPath(found));
    }
  }
  // --- Modules -------------------------------------------------------------
  /**
   * The module section is a search box, not a listing.
   *
   * A full list of every module is dozens of rows of noise in a sidebar this
   * narrow, and it pushes today's timeline -- the part that changes -- off the
   * screen. Nothing is drawn until there is a query to answer, which also means
   * the list is not fetched when the panel merely opens; on desktop that fetch
   * starts a Python process.
   */
  buildModules(root) {
    const details = root.createEl("details", { cls: "memory-tool-section" });
    details.setAttr("open", "");
    const summary = details.createEl("summary");
    summary.createSpan({ text: "\uBAA8\uB4C8 \uAC80\uC0C9" });
    const refresh = summary.createSpan({ cls: "memory-tool-section-action" });
    (0, import_obsidian6.setIcon)(refresh, "refresh-cw");
    refresh.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      void this.reloadModules();
    });
    this.moduleFilter = details.createEl("input", {
      cls: "memory-tool-module-filter",
      attr: { type: "text", placeholder: "\uBAA8\uB4C8 \uC774\uB984 \uAC80\uC0C9..." }
    });
    this.moduleFilter.addEventListener("input", () => void this.renderModules());
    this.moduleList = details.createDiv({ cls: "memory-tool-modules" });
  }
  /** Drop the cache and fetch again, then redraw whatever is on screen. */
  async reloadModules() {
    this.modules = null;
    await this.renderModules();
  }
  /**
   * Load the module list once and keep it.
   *
   * Returns null while another call is already loading, so a fast typist does
   * not start several CLI calls for the same list.
   */
  async loadModules() {
    if (this.modules !== null)
      return this.modules;
    if (this.loadingModules)
      return null;
    this.loadingModules = true;
    try {
      this.modules = await this.host.listModules();
      return this.modules;
    } finally {
      this.loadingModules = false;
    }
  }
  async renderModules() {
    const filter = this.moduleFilter.value.trim().toLowerCase();
    if (!filter) {
      this.moduleList.empty();
      this.moduleList.createDiv({
        cls: "memory-tool-empty",
        text: "\uAC80\uC0C9\uC5B4\uB97C \uC785\uB825\uD558\uBA74 \uBAA8\uB4C8\uC774 \uB098\uD0C0\uB0A9\uB2C8\uB2E4."
      });
      return;
    }
    if (this.modules === null) {
      this.moduleList.empty();
      this.moduleList.createDiv({ cls: "memory-tool-empty", text: "\uBD88\uB7EC\uC624\uB294 \uC911..." });
      const loaded = await this.loadModules();
      if (loaded === null)
        return;
      if (this.moduleFilter.value.trim().toLowerCase() !== filter) {
        void this.renderModules();
        return;
      }
    }
    const all = this.modules ?? [];
    const shown = all.filter((m) => m.toLowerCase().includes(filter));
    this.moduleList.empty();
    if (shown.length === 0) {
      this.moduleList.createDiv({
        cls: "memory-tool-empty",
        text: all.length === 0 ? "\uBAA8\uB4C8\uC774 \uC5C6\uC2B5\uB2C8\uB2E4." : "\uC77C\uCE58\uD558\uB294 \uBAA8\uB4C8\uC774 \uC5C6\uC2B5\uB2C8\uB2E4."
      });
      return;
    }
    for (const name of shown) {
      const row = this.moduleList.createDiv({ cls: "memory-tool-module", text: name });
      row.addEventListener("click", () => void this.openModule(name));
    }
  }
  async openModule(name) {
    for (const path of moduleCandidatePaths(this.host.basePrefix, name)) {
      if (await this.openPath(path))
        return;
    }
    new import_obsidian6.Notice(`'${name}' \uC744(\uB97C) \uC774 vault\uC5D0\uC11C \uCC3E\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4. Knowledge Base Folder \uC124\uC815\uC744 \uD655\uC778\uD558\uC138\uC694.`, 8e3);
  }
  /**
   * Open a vault-relative path in the main editor.
   *
   * Falls back to the adapter check because the knowledge base commonly lives in
   * a dot-folder, which Obsidian's file index skips -- getAbstractFileByPath
   * returns null there even though the file exists.
   */
  async openPath(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file instanceof import_obsidian6.TFile) {
      await this.app.workspace.getLeaf(false).openFile(file);
      return true;
    }
    return false;
  }
  // --- Actions -------------------------------------------------------------
  buildActions(root) {
    const details = root.createEl("details", { cls: "memory-tool-section" });
    details.createEl("summary").createSpan({ text: "\uB3C4\uAD6C" });
    const body = details.createDiv({ cls: "memory-tool-actions" });
    if (!this.host.cliAvailable()) {
      body.createDiv({
        cls: "memory-tool-empty",
        text: "\uCEE8\uD14D\uC2A4\uD2B8 \uC0DD\uC131\xB7\uACBD\uB85C \uC810\uAC80\xB7\uC778\uB371\uC2A4\uB294 Python CLI \uAC00 \uD544\uC694\uD574 \uC774 \uAE30\uAE30\uC5D0\uC11C\uB294 \uC4F8 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4. \uAE30\uB85D\uC740 \uC815\uC0C1 \uC800\uC7A5\uB418\uBA70, \uB370\uC2A4\uD06C\uD1B1\uC5D0\uC11C vault \uB97C \uC5F4\uBA74 \uAC80\uC0C9 \uC778\uB371\uC2A4\uAC00 \uB530\uB77C\uC7A1\uC2B5\uB2C8\uB2E4."
      });
      body.createDiv({
        cls: "memory-tool-base-note",
        text: `Base: ${describePrefix(this.host.basePrefix)}`
      });
      return;
    }
    this.actionButton(body, "AI \uCEE8\uD14D\uC2A4\uD2B8 \uC0DD\uC131 (mcontext)", async () => {
      new import_obsidian6.Notice("\uCEE8\uD14D\uC2A4\uD2B8 \uC0DD\uC131 \uC911...");
      await this.host.cli.buildContext();
      new import_obsidian6.Notice("\uCEE8\uD14D\uC2A4\uD2B8 \uC0DD\uC131 \uC644\uB8CC (.claude/memory-context.md)");
    });
    this.actionButton(body, "\uBAA8\uB4C8 \uACBD\uB85C \uC810\uAC80 (mcheck)", async () => {
      new import_obsidian6.Notice("\uACBD\uB85C \uC810\uAC80 \uC911...");
      const res = await this.host.cli.checkHealth();
      new import_obsidian6.Notice(res || "\uC810\uAC80 \uC644\uB8CC.");
    });
    this.actionButton(body, "\uAC80\uC0C9 \uC778\uB371\uC2A4 \uB3D9\uAE30\uD654", async () => {
      const pending = this.host.pendingIndexCount();
      await this.host.syncIndex();
      new import_obsidian6.Notice(pending > 0 ? `\uC778\uB371\uC2A4 \uB3D9\uAE30\uD654 \uC644\uB8CC (${pending}\uAC74 \uBC18\uC601)` : "\uC778\uB371\uC2A4 \uB3D9\uAE30\uD654 \uC644\uB8CC");
    });
    body.createDiv({
      cls: "memory-tool-base-note",
      text: `Base: ${describePrefix(this.host.basePrefix)}`
    });
  }
  actionButton(parent, label, run) {
    const btn = parent.createEl("button", { text: label });
    btn.addEventListener("click", async () => {
      btn.setAttr("disabled", "true");
      try {
        await run();
      } catch (err) {
        new import_obsidian6.Notice(`\uC2E4\uD328: ${err.message}`);
      } finally {
        btn.removeAttribute("disabled");
      }
    });
  }
};

// src/timeline/directWriter.ts
var import_obsidian7 = require("obsidian");
function basename(path) {
  return path.split("/").filter(Boolean).pop() ?? path;
}
async function readParsedConfig(adapter, basePrefix) {
  const path = underBase(basePrefix, "config.yaml");
  try {
    if (!await adapter.exists(path))
      return null;
    return (0, import_obsidian7.parseYaml)(await adapter.read(path));
  } catch {
    return null;
  }
}
async function inferFilenameLayout(adapter, basePrefix, when) {
  const namesIn = async (dir) => {
    try {
      if (!await adapter.exists(dir))
        return [];
      return (await adapter.list(dir)).files.map(basename);
    } catch {
      return [];
    }
  };
  for (const dir of timelineMonthDirs(basePrefix, when)) {
    const found = layoutFromFilenames(await namesIn(dir));
    if (found)
      return found;
  }
  for (const root of timelineRootDirs(basePrefix)) {
    let folders;
    try {
      if (!await adapter.exists(root))
        continue;
      folders = (await adapter.list(root)).folders.map(basename);
    } catch {
      continue;
    }
    for (const month of sortMonthDirs(folders)) {
      const found = layoutFromFilenames(await namesIn(`${root}/${month}`));
      if (found)
        return found;
    }
  }
  return null;
}
async function resolveFilenameLayout(adapter, basePrefix, when = new Date(), setting = "auto", parsed) {
  if (setting === "day" || setting === "date") {
    return { layout: setting, source: "setting" };
  }
  const config = parsed === void 0 ? await readParsedConfig(adapter, basePrefix) : parsed;
  const stated = configuredFilenameLayout(config);
  if (stated)
    return { layout: stated, source: "config" };
  const inferred = await inferFilenameLayout(adapter, basePrefix, when);
  if (inferred)
    return { layout: inferred, source: "files" };
  return { layout: DEFAULT_FILENAME_LAYOUT, source: "default" };
}
async function recordDirect(adapter, basePrefix, message, options = {}) {
  const { tags = [], when = new Date(), layoutSetting = "auto" } = options;
  const text = sanitizeMessage(message);
  if (!text)
    throw new Error("Cannot record an empty message.");
  const parsed = await readParsedConfig(adapter, basePrefix);
  const config = parsed === null ? { ...DEFAULT_TIMELINE_CONFIG } : timelineConfigFrom(parsed);
  const layout = await resolveFilenameLayout(adapter, basePrefix, when, layoutSetting, parsed);
  let path = null;
  for (const candidate of candidatePaths(basePrefix, when)) {
    if (await adapter.exists(candidate)) {
      path = candidate;
      break;
    }
  }
  const created = path === null;
  if (path === null) {
    const dir = timelineDir(basePrefix, when);
    path = `${dir}/${filenameFor(when, layout.layout)}`;
    if (!await adapter.exists(dir)) {
      await adapter.mkdir(dir);
    }
  }
  const entry = formatEntry(when, text, tags, config.tagFormat);
  const body = created ? newFileBody(when, entry) : appendEntry(await adapter.read(path), entry);
  await adapter.write(path, body);
  return { path, entry, created, layout };
}

// src/vaultScan.ts
var BASE_CANDIDATES = ["", ".memory", "memory"];
var BASE_MARKERS = ["timeline", "modules"];
var LEGACY_FILES = /* @__PURE__ */ new Set([
  "module.md",
  "current.md",
  "decisions.md",
  "dependencies.md",
  "interface.md"
]);
async function probeBasePrefix(adapter, candidates = BASE_CANDIDATES) {
  for (const prefix of candidates) {
    const checks = await Promise.all(
      BASE_MARKERS.map((marker) => adapter.exists(underBase(prefix, marker)))
    );
    if (checks.every(Boolean))
      return prefix;
  }
  return null;
}
function basename2(path) {
  return path.split("/").filter(Boolean).pop() ?? path;
}
function stem(name) {
  return name.endsWith(".md") ? name.slice(0, -3) : name;
}
function isIgnoredFile(name) {
  if (name.startsWith("_"))
    return true;
  if (name === "MIGRATION-SUMMARY.md")
    return true;
  const base = stem(name);
  return base === base.toUpperCase() && /[A-Z]/.test(base);
}
async function listModules(adapter, basePrefix) {
  const root = underBase(basePrefix, "modules");
  if (!await adapter.exists(root))
    return [];
  const found = /* @__PURE__ */ new Set();
  const walk = async (dir, relative) => {
    let listing;
    try {
      listing = await adapter.list(dir);
    } catch {
      return;
    }
    for (const filePath of listing.files) {
      const name = basename2(filePath);
      if (!name.endsWith(".md") || isIgnoredFile(name))
        continue;
      if (LEGACY_FILES.has(name)) {
        if (relative)
          found.add(relative);
        continue;
      }
      if (relative && stem(name) === basename2(relative)) {
        found.add(relative);
        continue;
      }
      const flat = relative ? `${relative}/${stem(name)}` : stem(name);
      found.add(flat);
    }
    for (const folderPath of listing.folders) {
      const name = basename2(folderPath);
      if (name === "archive" || name.startsWith("."))
        continue;
      await walk(folderPath, relative ? `${relative}/${name}` : name);
    }
  };
  await walk(root, "");
  return [...found].sort();
}
function asScanAdapter(adapter) {
  return {
    exists: (path) => adapter.exists(path),
    list: (path) => adapter.list(path)
  };
}

// src/main.ts
var DEFAULT_SETTINGS = {
  pythonPath: "python",
  baseFolder: "",
  directCapture: true,
  filenameLayout: "auto",
  indexSyncThreshold: 10,
  pendingIndex: 0
};
var MemoryToolPlugin = class extends import_obsidian8.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.cli = new MemoryToolCli();
    /**
     * Knowledge base location as a vault-relative prefix.
     * "" means the vault root itself is the base folder.
     */
    this.basePrefix = DEFAULT_BASE;
    /** Absolute path of the vault root. */
    this.vaultRoot = "";
    /** Guards against two index syncs overlapping. */
    this.syncing = false;
  }
  async onload() {
    await this.loadSettings();
    this.vaultRoot = this.app.vault.adapter.getBasePath ? this.app.vault.adapter.getBasePath() : "";
    this.cli.setCwd(this.vaultRoot);
    this.cli.setPythonPath(this.settings.pythonPath);
    await this.resolveBaseFolder();
    this.registerView(MEMORY_PANEL_VIEW, (leaf) => new MemoryPanelView(leaf, this));
    this.ribbonButton("pencil", "\uD0C0\uC784\uB77C\uC778 \uAE30\uB85D (m)", () => {
      new RecordModal(this.app, (msg) => this.recordEntry(msg)).open();
    });
    this.ribbonButton("clock", "Memory Tool \uD328\uB110 \uC5F4\uAE30", () => {
      void this.activatePanel();
    });
    this.addCommand({
      id: "open-panel",
      name: "Memory Tool \uD328\uB110 \uC5F4\uAE30",
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "m" }],
      callback: () => {
        void this.activatePanel();
      }
    });
    this.addCommand({
      id: "record-timeline",
      name: "\uD0C0\uC784\uB77C\uC778 \uAE30\uB85D (\uBE60\uB978 \uC785\uB825)",
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "j" }],
      callback: () => {
        new RecordModal(this.app, (msg) => this.recordEntry(msg)).open();
      }
    });
    this.addCommand({
      id: "go-to-module",
      name: "\uBAA8\uB4C8\uB85C \uC774\uB3D9",
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "g" }],
      callback: () => {
        new ModuleSuggestModal(
          this.app,
          () => this.listModules(),
          () => this.basePrefix
        ).open();
      }
    });
    this.addCommand({
      id: "show-filename-layout",
      name: "\uD0C0\uC784\uB77C\uC778 \uD30C\uC77C\uBA85 \uADDC\uCE59 \uD655\uC778",
      callback: async () => {
        const resolved = await resolveFilenameLayout(
          this.app.vault.adapter,
          this.basePrefix,
          new Date(),
          this.settings.filenameLayout
        );
        const sources = {
          setting: "\uD50C\uB7EC\uADF8\uC778 \uC124\uC815",
          config: "config.yaml",
          files: "\uAE30\uC874 \uD0C0\uC784\uB77C\uC778 \uD30C\uC77C\uBA85",
          default: "\uAE30\uBCF8\uAC12"
        };
        new import_obsidian8.Notice(
          `\uC624\uB298 \uC0C8 \uD30C\uC77C\uC744 \uB9CC\uB4E4\uBA74: ${filenameFor(new Date(), resolved.layout)}
\uADFC\uAC70: ${sources[resolved.source]} \xB7 Base: ${describePrefix(this.basePrefix)}`,
          1e4
        );
      }
    });
    this.addCommand({
      id: "show-base-folder",
      name: "\uC9C0\uC2DD \uBCA0\uC774\uC2A4 \uD3F4\uB354 \uD655\uC778 (mbase)",
      callback: async () => {
        await this.resolveBaseFolder();
        new import_obsidian8.Notice(`Knowledge base folder: ${describePrefix(this.basePrefix)}`);
      }
    });
    if (this.cli.isAvailable()) {
      this.registerCliCommands();
      this.registerFolderMenu();
    }
    this.addSettingTab(new MemoryToolSettingTab(this.app, this));
    if (this.settings.pendingIndex > 0 && this.cli.isAvailable()) {
      this.app.workspace.onLayoutReady(() => void this.syncIndex().catch(() => {
      }));
    }
  }
  /**
   * "여기에 모듈 생성" on a folder inside the modules tree.
   *
   * Typing the parent path by hand is the part of module creation that is both
   * tedious and easy to get wrong, and the file explorer already knows it.
   * Folders outside `<base>/modules` get no entry: modules cannot live there,
   * so offering it would only produce an error later.
   */
  registerFolderMenu() {
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!("children" in file))
          return;
        const prefix = modulePrefixFromFolder(this.basePrefix, file.path);
        if (prefix === null)
          return;
        menu.addItem((item) => {
          item.setTitle("\uC5EC\uAE30\uC5D0 \uBAA8\uB4C8 \uC0DD\uC131").setIcon("folder-plus").onClick(() => {
            new CreateModuleModal(
              this.app,
              this.cli,
              () => this.basePrefix,
              prefix
            ).open();
          });
        });
      })
    );
  }
  /** Commands that require the Python CLI; desktop only. */
  registerCliCommands() {
    this.addCommand({
      id: "create-module",
      name: "\uBAA8\uB4C8 \uC0DD\uC131",
      callback: () => {
        new CreateModuleModal(this.app, this.cli, () => this.basePrefix).open();
      }
    });
    this.addCommand({
      id: "grow-module",
      name: "\uBAA8\uB4C8 \uC804\uCCB4 \uACE8\uACA9 \uBD99\uC774\uAE30 (mmodule grow)",
      callback: () => {
        const open = this.app.workspace.getActiveFile();
        const name = open ? moduleNameFromPath(this.basePrefix, open.path) : null;
        if (name) {
          void this.growModule(name);
          return;
        }
        new import_obsidian8.Notice("\uC5F4\uB9B0 \uBB38\uC11C\uAC00 \uBAA8\uB4C8\uC774 \uC544\uB2D9\uB2C8\uB2E4. \uBAA9\uB85D\uC5D0\uC11C \uACE0\uB974\uC138\uC694.");
        new ModuleSuggestModal(
          this.app,
          () => this.listModules(),
          () => this.basePrefix,
          (chosen) => void this.growModule(chosen)
        ).open();
      }
    });
    this.addCommand({
      id: "build-context",
      name: "AI \uCEE8\uD14D\uC2A4\uD2B8 \uC0DD\uC131 (mcontext)",
      callback: async () => {
        new import_obsidian8.Notice("\uCEE8\uD14D\uC2A4\uD2B8 \uC0DD\uC131 \uC911...");
        try {
          await this.cli.buildContext();
          new import_obsidian8.Notice("\uCEE8\uD14D\uC2A4\uD2B8 \uC0DD\uC131 \uC644\uB8CC (.claude/memory-context.md)");
        } catch (err) {
          new import_obsidian8.Notice(`\uCEE8\uD14D\uC2A4\uD2B8 \uC0DD\uC131 \uC2E4\uD328: ${err.message}`);
        }
      }
    });
    this.addCommand({
      id: "check-path-health",
      name: "\uBAA8\uB4C8 \uACBD\uB85C \uC810\uAC80 (mcheck)",
      callback: async () => {
        new import_obsidian8.Notice("\uACBD\uB85C \uC810\uAC80 \uC911...");
        try {
          new import_obsidian8.Notice(await this.cli.checkHealth() || "\uC810\uAC80 \uC644\uB8CC.");
        } catch (err) {
          new import_obsidian8.Notice(`\uC810\uAC80 \uC2E4\uD328: ${err.message}`);
        }
      }
    });
    this.addCommand({
      id: "ask-memory",
      name: "\uAE30\uC5B5\uC5D0 \uC9C8\uBB38\uD558\uAE30 (mask)",
      callback: () => {
        new AskModal(this.app, this.cli, () => this.basePrefix).open();
      }
    });
    this.addCommand({
      id: "sync-index",
      name: "\uAC80\uC0C9 \uC778\uB371\uC2A4 \uB3D9\uAE30\uD654",
      callback: async () => {
        const pending = this.settings.pendingIndex;
        try {
          await this.syncIndex();
          new import_obsidian8.Notice(pending > 0 ? `\uC778\uB371\uC2A4 \uB3D9\uAE30\uD654 \uC644\uB8CC (${pending}\uAC74)` : "\uC778\uB371\uC2A4 \uB3D9\uAE30\uD654 \uC644\uB8CC");
        } catch (err) {
          new import_obsidian8.Notice(`\uC778\uB371\uC2A4 \uB3D9\uAE30\uD654 \uC2E4\uD328: ${err.message}`);
        }
      }
    });
  }
  onunload() {
  }
  /**
   * Add a ribbon button that cannot fail silently.
   *
   * Two failure modes are covered, both of which look identical to the user --
   * "the button does nothing":
   *
   *   1. An icon name Obsidian does not know renders no SVG, leaving a blank
   *      strip of ribbon that is easy to miss and easy to mis-click. If nothing
   *      was drawn, a visible label is written into the button instead.
   *   2. An exception thrown inside the callback is swallowed by the event
   *      dispatcher, so the click appears to do nothing at all. Reporting it as
   *      a notice is the difference between a bug and a mystery.
   */
  ribbonButton(icon, title, action) {
    const el = this.addRibbonIcon(icon, title, () => {
      try {
        action();
      } catch (err) {
        console.error("[memory_tool] ribbon action failed", err);
        new import_obsidian8.Notice(`${title} \uC2E4\uD328: ${err?.message ?? err}`, 1e4);
      }
    });
    if (!el.querySelector("svg")) {
      el.addClass("memory-tool-ribbon-fallback");
      el.setText(title.slice(0, 2));
    }
  }
  /** Reveal the side panel, creating it in the right sidebar if needed. */
  async activatePanel() {
    const { workspace } = this.app;
    try {
      let leaf = workspace.getLeavesOfType(MEMORY_PANEL_VIEW)[0] ?? null;
      if (!leaf) {
        leaf = workspace.getRightLeaf(false) ?? workspace.getLeaf(true);
        if (!leaf) {
          new import_obsidian8.Notice("\uD328\uB110\uC744 \uC5F4 \uC790\uB9AC\uB97C \uCC3E\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4.");
          return;
        }
        await leaf.setViewState({ type: MEMORY_PANEL_VIEW, active: true });
      }
      await workspace.revealLeaf(leaf);
      const view = leaf.view;
      if (view instanceof MemoryPanelView)
        view.focusCapture();
    } catch (err) {
      console.error("[memory_tool] failed to open the panel", err);
      new import_obsidian8.Notice(`\uD328\uB110 \uC5F4\uAE30 \uC2E4\uD328: ${err?.message ?? err}`, 1e4);
    }
  }
  // --- PanelHost -----------------------------------------------------------
  /**
   * Record one timeline entry.
   *
   * Direct write is the default because the CLI round-trip is dominated by
   * Python start-up (~1.6s measured) rather than by the work itself. The CLI
   * path stays available for anyone who would rather have the indexer run
   * inline, and is used automatically as a fallback if the direct write fails.
   */
  async recordEntry(message) {
    if (!this.settings.directCapture) {
      await this.cli.recordTimeline(message);
      return { path: "", entry: message };
    }
    try {
      const result = await recordDirect(this.app.vault.adapter, this.basePrefix, message, {
        layoutSetting: this.settings.filenameLayout
      });
      this.settings.pendingIndex += 1;
      await this.saveData(this.settings);
      const threshold = this.settings.indexSyncThreshold;
      if (threshold > 0 && this.settings.pendingIndex >= threshold) {
        void this.syncIndex().catch(() => {
        });
      }
      return { path: result.path, entry: result.entry };
    } catch (err) {
      await this.cli.recordTimeline(message);
      new import_obsidian8.Notice(`\uC9C1\uC811 \uAE30\uB85D \uC2E4\uD328\uB85C CLI\uB85C \uAE30\uB85D\uD588\uC2B5\uB2C8\uB2E4: ${err.message}`, 8e3);
      return { path: "", entry: message };
    }
  }
  pendingIndexCount() {
    return this.settings.pendingIndex;
  }
  /** Whether CLI-backed features can run (false on mobile). */
  cliAvailable() {
    return this.cli.isAvailable();
  }
  /**
   * List modules, preferring the CLI and falling back to a vault scan.
   *
   * The scan mirrors the CLI's discovery rules, so mobile gets the same list
   * without Python. It is the fallback rather than the default because the CLI
   * remains the definition of what counts as a module.
   */
  /**
   * Append the skeleton sections a module does not have yet.
   *
   * Reports the section names rather than a bare success: the point of the
   * command is that something was added, and "nothing to add" is a real and
   * unremarkable outcome that should not read as a failure.
   */
  async growModule(name) {
    new import_obsidian8.Notice(`'${name}' \uACE8\uACA9 \uD655\uC7A5 \uC911...`);
    try {
      const output = await this.cli.growModule(name);
      const added = /Added (\d+) section\(s\): (.+)/.exec(output);
      if (added) {
        new import_obsidian8.Notice(`${name}: ${added[2]} \uC808\uC744 \uBD99\uC600\uC2B5\uB2C8\uB2E4.`, 6e3);
      } else {
        new import_obsidian8.Notice(`${name}: \uC774\uBBF8 \uBAA8\uB4E0 \uC808\uC774 \uC788\uC2B5\uB2C8\uB2E4. \uBC14\uB010 \uAC83\uC774 \uC5C6\uC2B5\uB2C8\uB2E4.`, 6e3);
      }
    } catch (err) {
      new import_obsidian8.Notice(`\uACE8\uACA9 \uD655\uC7A5 \uC2E4\uD328: ${err.message}`, 8e3);
    }
  }
  async listModules() {
    if (this.cli.isAvailable()) {
      const fromCli = await this.cli.listModules();
      if (fromCli.length > 0)
        return fromCli;
    }
    return listModules(asScanAdapter(this.app.vault.adapter), this.basePrefix);
  }
  /**
   * Bring the SQLite search index up to date with directly-written entries.
   *
   * On mobile this is a no-op: the index is a desktop artifact and the pending
   * count is deliberately preserved, so the entries written on the phone are
   * indexed the next time the vault is opened on a machine that can.
   */
  async syncIndex() {
    if (!this.cli.isAvailable())
      return;
    if (this.syncing)
      return;
    this.syncing = true;
    try {
      await this.cli.syncIndex();
      this.settings.pendingIndex = 0;
      await this.saveData(this.settings);
    } finally {
      this.syncing = false;
    }
  }
  // --- Base folder ---------------------------------------------------------
  /**
   * Determine where the knowledge base sits *relative to the vault root*.
   *
   * memory_tool reports the base folder relative to the project root, which is
   * not the same reference point: when the vault is the base folder itself, the
   * correct prefix is "" even though memory_tool reports ".memory". Using the
   * name directly produced .memory/.memory/... and silently found nothing.
   * Working from the absolute path avoids that entirely.
   *
   * A manual override wins. Detection failure is not fatal -- the plugin falls
   * back to the historical default so its other commands keep working.
   */
  async resolveBaseFolder() {
    const override = this.settings.baseFolder.trim();
    if (override) {
      this.basePrefix = normalizePrefix(override);
      return;
    }
    if (!this.cli.isAvailable()) {
      if (!await this.useProbedBase()) {
        new import_obsidian8.Notice(
          "memory_tool: \uC774 vault \uC548\uC5D0\uC11C \uC9C0\uC2DD \uBCA0\uC774\uC2A4\uB97C \uCC3E\uC9C0 \uBABB\uD588\uC2B5\uB2C8\uB2E4 (timeline/ \uACFC modules/ \uB97C \uAC00\uC9C4 \uD3F4\uB354). \uC124\uC815\uC5D0\uC11C \uC9C1\uC811 \uC9C0\uC815\uD558\uC138\uC694.",
          1e4
        );
      }
      return;
    }
    let info;
    try {
      info = await this.cli.getBaseInfo();
    } catch {
      if (!await this.useProbedBase()) {
        new import_obsidian8.Notice(
          `memory_tool: could not detect the knowledge base folder, assuming ${DEFAULT_BASE}/. Set it manually in the plugin settings if that is wrong.`
        );
      }
      return;
    }
    const prefix = vaultRelativeBase(this.vaultRoot, info.base);
    if (prefix === null) {
      const probed = await this.useProbedBase();
      new import_obsidian8.Notice(
        `memory_tool: the knowledge base (${info.base}) is outside this vault. ` + (probed ? `Using ${describePrefix(this.basePrefix)} in this vault instead.` : "Its files cannot be opened here. Open that folder as the vault, or set the folder manually in the plugin settings."),
        1e4
      );
      return;
    }
    this.basePrefix = prefix;
    if (info.source === "nested-artifact") {
      new import_obsidian8.Notice(
        "memory_tool: a leftover nested .memory/ folder was found and ignored. Entries recorded there by older versions are not visible in normal commands -- run 'mbase show' for details.",
        1e4
      );
    }
  }
  /**
   * Fall back to searching the vault for the knowledge base.
   *
   * Sets `basePrefix` to the historical default when nothing is found, so the
   * caller only has to decide what to say. Returns whether a base was actually
   * located.
   */
  async useProbedBase() {
    const probed = await probeBasePrefix(asScanAdapter(this.app.vault.adapter));
    this.basePrefix = probed ?? DEFAULT_BASE;
    return probed !== null;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.cli.setPythonPath(this.settings.pythonPath);
    await this.resolveBaseFolder();
  }
};
var MemoryToolSettingTab = class extends import_obsidian8.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian8.Setting(containerEl).setName("Python Executable Path").setDesc("Path to Python executable or virtual environment (default: 'python')").addText(
      (text) => text.setPlaceholder("python").setValue(this.plugin.settings.pythonPath).onChange(async (value) => {
        this.plugin.settings.pythonPath = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian8.Setting(containerEl).setName("Knowledge Base Folder").setDesc(
      `Folder holding timeline/ and modules/, relative to the vault root. Leave empty to detect it automatically (currently: ${describePrefix(this.plugin.basePrefix)}). Use "." when the vault root itself is the knowledge base \u2014 which is the case if you opened the .memory folder as your vault.`
    ).addText(
      (text) => text.setPlaceholder("(auto-detect)").setValue(this.plugin.settings.baseFolder).onChange(async (value) => {
        this.plugin.settings.baseFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian8.Setting(containerEl).setName("\uCEA1\uCC98").setHeading();
    new import_obsidian8.Setting(containerEl).setName("Python \uC5C6\uC774 \uC9C1\uC811 \uAE30\uB85D").setDesc(
      "\uD0C0\uC784\uB77C\uC778 \uD56D\uBAA9\uC744 \uD50C\uB7EC\uADF8\uC778\uC774 \uC9C1\uC811 \uD30C\uC77C\uC5D0 \uC501\uB2C8\uB2E4. CLI \uACBD\uC720\uB294 \uD56D\uBAA9\uB2F9 Python \uC2DC\uC791 \uBE44\uC6A9(\uC57D 1.6\uCD08)\uC774 \uBD99\uC2B5\uB2C8\uB2E4. \uB044\uBA74 \uD56D\uC0C1 CLI\uB97C \uC501\uB2C8\uB2E4."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.directCapture).onChange(async (value) => {
        this.plugin.settings.directCapture = value;
        await this.plugin.saveSettings();
      })
    );
    const layoutSetting = new import_obsidian8.Setting(containerEl).setName("\uD0C0\uC784\uB77C\uC778 \uD30C\uC77C\uBA85").setDesc("\uD655\uC778 \uC911...").addDropdown(
      (drop) => drop.addOption("auto", "\uC790\uB3D9 (config.yaml \u2192 \uAE30\uC874 \uD30C\uC77C\uBA85)").addOption("date", "2026-08-20.md (date)").addOption("day", "20.md (day)").setValue(this.plugin.settings.filenameLayout).onChange(async (value) => {
        this.plugin.settings.filenameLayout = value;
        await this.plugin.saveSettings();
        void describeLayout();
      })
    );
    const describeLayout = async () => {
      const resolved = await resolveFilenameLayout(
        this.app.vault.adapter,
        this.plugin.basePrefix,
        new Date(),
        this.plugin.settings.filenameLayout
      );
      const sources = {
        setting: "\uC774 \uC124\uC815",
        config: "config.yaml",
        files: "\uAE30\uC874 \uD0C0\uC784\uB77C\uC778 \uD30C\uC77C\uBA85",
        default: "\uAE30\uBCF8\uAC12"
      };
      layoutSetting.setDesc(
        `\uC0C8 \uD30C\uC77C\uC744 \uB9CC\uB4E4 \uB54C \uC4F0\uB294 \uC774\uB984\uC785\uB2C8\uB2E4. \uC9C0\uAE08 \uAE30\uC900\uC73C\uB85C\uB294 ${filenameFor(new Date(), resolved.layout)} \uB85C \uB9CC\uB4E4\uC5B4\uC9C0\uBA70, \uADFC\uAC70\uB294 ${sources[resolved.source]} \uC785\uB2C8\uB2E4.`
      );
    };
    void describeLayout();
    new import_obsidian8.Setting(containerEl).setName("\uC778\uB371\uC2A4 \uC790\uB3D9 \uB3D9\uAE30\uD654 \uAE30\uC900").setDesc(
      `\uC9C1\uC811 \uAE30\uB85D\uC774 \uC774 \uAC1C\uC218\uB9CC\uD07C \uC313\uC774\uBA74 \uAC80\uC0C9 \uC778\uB371\uC2A4\uB97C \uC790\uB3D9\uC73C\uB85C \uAC31\uC2E0\uD569\uB2C8\uB2E4. 0\uC774\uBA74 \uC218\uB3D9\uC73C\uB85C\uB9CC \uAC31\uC2E0\uD569\uB2C8\uB2E4. \uD604\uC7AC \uBBF8\uBC18\uC601: ${this.plugin.settings.pendingIndex}\uAC74.`
    ).addText(
      (text) => text.setPlaceholder("10").setValue(String(this.plugin.settings.indexSyncThreshold)).onChange(async (value) => {
        const parsed = Number.parseInt(value, 10);
        this.plugin.settings.indexSyncThreshold = Number.isFinite(parsed) && parsed >= 0 ? parsed : 0;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("p", {
      text: "\uB2E8\uCD95\uD0A4\uAC00 \uBC18\uC751\uD558\uC9C0 \uC54A\uC73C\uBA74 \uC124\uC815 \u2192 \uB2E8\uCD95\uD0A4\uC5D0\uC11C \uD574\uB2F9 \uBA85\uB839\uC758 \uAE30\uC874 Ctrl+Alt \uC870\uD569\uC744 \uC9C0\uC6B0\uACE0 \uB2E4\uC2DC \uC9C0\uC815\uD558\uC138\uC694. Windows\uC5D0\uC11C Ctrl+Alt\uB294 AltGr\uB85C \uD574\uC11D\uB418\uC5B4 \uD55C\uAE00 IME\uB098 \uB2E4\uB978 \uC571\uC758 \uC804\uC5ED \uB2E8\uCD95\uD0A4\uAC00 \uBA3C\uC800 \uAC00\uB85C\uCC55\uB2C8\uB2E4.",
      cls: "setting-item-description"
    });
    containerEl.createEl("p", {
      text: "To change where memory_tool itself stores the knowledge base, run 'mbase set <name>' in the vault folder. This setting only tells the plugin where to look.",
      cls: "setting-item-description"
    });
  }
};
