"""Initialization functionality for .memory/ structure."""

from datetime import datetime
from pathlib import Path
from typing import Optional
import yaml


class InitializationError(Exception):
    """Base exception for initialization operations."""
    pass


class AlreadyInitializedError(InitializationError):
    """Raised when .memory/ already exists."""
    pass


class MemoryInitializer:
    """Initializer for .memory/ structure."""

    def __init__(self, base_path: Optional[Path] = None):
        """Initialize memory initializer.

        Args:
            base_path: Base path for project. Defaults to current directory.
        """
        if base_path is None:
            base_path = Path.cwd()
        self.base_path = Path(base_path)
        self.memory_path = self.base_path / ".memory"

    def is_initialized(self) -> bool:
        """Check if .memory/ already exists.

        Returns:
            True if .memory/ directory exists
        """
        return self.memory_path.exists()

    def get_structure(self) -> dict:
        """Get the directory structure to create.

        Returns:
            Dictionary mapping paths to types ('dir' or 'file')
        """
        return {
            ".memory": "dir",
            ".memory/timeline": "dir",
            ".memory/modules": "dir",
            ".memory/concepts": "dir",
            ".memory/templates": "dir",
            ".memory/.gitkeep": "file",
            ".memory/timeline/.gitkeep": "file",
            ".memory/modules/.gitkeep": "file",
            ".memory/concepts/.gitkeep": "file",
            ".memory/templates/.gitkeep": "file",
        }

    def create_config_yaml(self) -> Path:
        """Create initial config.yaml.

        Returns:
            Path to created config.yaml
        """
        config_path = self.memory_path / "config.yaml"

        config = {
            "version": "1.0",
            "timeline": {
                "auto_record": False,
                "granularity": "medium",
            },
            "context": {
                "auto_update": False,
                "recent_days": 3,
            },
            "modules": {
                "auto_update_current": False,
            },
            "search": {
                "default_scope": "local",
                "include_archived": False,
            },
        }

        with open(config_path, "w", encoding="utf-8") as f:
            yaml.dump(config, f, default_flow_style=False, sort_keys=False)

        return config_path

    def create_kb_lock(self, kb_path: Optional[str] = None) -> Optional[Path]:
        """Create kb.lock file pointing to knowledge base.

        Args:
            kb_path: Path to knowledge base (optional)

        Returns:
            Path to kb.lock if created, None otherwise
        """
        if kb_path is None:
            return None

        kb_lock_path = self.memory_path / "kb.lock"
        kb_lock_path.write_text(kb_path, encoding="utf-8")
        return kb_lock_path

    def create_readme(self) -> Path:
        """Create README.md explaining the structure.

        Returns:
            Path to created README.md
        """
        readme_path = self.memory_path / "README.md"

        content = f"""# .memory/

This directory contains the memory structure for this project.

**Created:** {datetime.now().strftime("%Y-%m-%d %H:%M")}

## Structure

- `timeline/` - Time-based records (YYYY-MM/DD.md)
- `modules/` - Module-based organization
- `concepts/` - Standalone concept documents
- `config.yaml` - Configuration settings

## Usage

```bash
# Record to timeline
m "Your message here"

# Search
ms "query"

# Build context for Claude Code
mcontext
```

## Philosophy

**Time First** - Capture first, organize later
**Lossless** - Record everything, lose nothing
**Minimal Friction** - Minimal input, defer organization

---

Generated by Memory Tool v0.1.0
"""

        readme_path.write_text(content, encoding="utf-8")
        return readme_path

    def create_claude_template(self) -> Path:
        """Create CLAUDE.md template for Claude Code integration.

        Returns:
            Path to created template file
        """
        template_path = self.memory_path / "templates" / "CLAUDE.md.template"

        content = """# For Claude Code 🤖

> **Template for integrating memory_tool with Claude Code**
>
> Copy relevant sections to your project's `CLAUDE.md` file.

---

## 🔗 Memory Tool Integration

**Before starting a session, read the memory context:**

```
Read .claude/memory-context.md (if exists)
```

This file contains auto-generated context from:
- Recent timeline entries (what's been happening)
- Current module states (what's active)
- Key decisions and concepts (what matters)

---

## 📚 Project Memory

**Auto-Generated Context:**
- `.claude/memory-context.md` - Current session context (auto-generated by `mcontext`)
  - Generated from: recent timeline + active modules + key decisions
  - Use this for understanding current project state
  - Regenerate with: `mcontext` command

**Manual Records:**
- `.memory/timeline/` - Time-based records (YYYY-MM/DD.md)
- `.memory/modules/` - Module-based organization
- `.memory/concepts/` - Standalone concept documents
- `.memory/modules/[module-name]/decisions.md` - Key decisions
- `.memory/modules/[module-name]/current.md` - Current state

---

## ⚡ Quick Commands

**Recording:**
```bash
m "message"                  # Record to timeline
```

**Search:**
```bash
ms "query"                   # Search local project
ms --with-kb "query"         # Search local + knowledge base
ms --all "query"             # Search all projects
```

**Context:**
```bash
mcontext                     # Generate .claude/memory-context.md
```

**Important:** Run `mcontext` before starting Claude Code to ensure fresh context!

---

## 🎯 Workflow

### Starting a Session
1. Update memory: `m "Starting work on [feature]"`
2. Generate context: `mcontext`
3. Start Claude Code
4. Claude automatically reads `.claude/memory-context.md`

### During Session
1. Record progress: `m "Implemented [feature]"`
2. Update module state: Edit `.memory/modules/[name]/current.md`
3. Regenerate if needed: `mcontext`

### Ending Session
1. Final record: `m "Session complete: [summary]"`
2. Update current state in modules
3. Document decisions in `.memory/modules/[name]/decisions.md`

---

## 📋 Customization

**Add your project-specific sections below:**

- Project overview
- Current status
- Technical details
- Team conventions
- etc.

---

**Generated by Memory Tool**
"""

        template_path.write_text(content, encoding="utf-8")
        return template_path

    def initialize(
        self,
        force: bool = False,
        kb_path: Optional[str] = None,
    ) -> dict:
        """Initialize .memory/ structure.

        Args:
            force: If True, reinitialize even if already exists
            kb_path: Optional path to knowledge base

        Returns:
            Dictionary with created paths

        Raises:
            AlreadyInitializedError: If already initialized and force=False
        """
        # Check if already initialized
        if self.is_initialized() and not force:
            raise AlreadyInitializedError(
                f".memory/ already exists at {self.memory_path}. "
                f"Use --force to reinitialize."
            )

        created = {
            "directories": [],
            "files": [],
        }

        # Create directory structure
        structure = self.get_structure()
        for rel_path, type_ in structure.items():
            full_path = self.base_path / rel_path

            if type_ == "dir":
                full_path.mkdir(parents=True, exist_ok=True)
                created["directories"].append(full_path)
            elif type_ == "file":
                full_path.parent.mkdir(parents=True, exist_ok=True)
                full_path.touch()
                created["files"].append(full_path)

        # Create config.yaml
        config_path = self.create_config_yaml()
        created["files"].append(config_path)

        # Create README.md
        readme_path = self.create_readme()
        created["files"].append(readme_path)

        # Create CLAUDE.md template
        template_path = self.create_claude_template()
        created["files"].append(template_path)

        # Create kb.lock if requested
        if kb_path:
            kb_lock_path = self.create_kb_lock(kb_path)
            if kb_lock_path:
                created["files"].append(kb_lock_path)

        return created
